.travis.yml, Makefile, requirements3.txt
Travis will execute pre-commit checks by building and testing our code.
=> Added Travis-CI configuration file

.travis.yml
Added deploy step.
Travis file has been automatically re-formatted via travis CLI.
=> [DPTOOLS-1515] Register to Pypi

.travis.yml, setup.py
- Make it only run on python (can be tested during deploy step)
- Updated pypi package name and version.
=> [DPTOOLS-1515] Travis staging test and deploy

.travis.yml
Previous attempt registered to Pypi successfully.
https://pypi.org/project/amundsen-frontend/
However, it's still invoking deploy in node js. This is not affecting deployment but to make it clean.
=> [DPTOOLS-1803] Using conditional deployment via ENVVAR

amundsen_application/__init__.py, amundsen_application/api/announcements/v0.py, amundsen_application/api/mail/v0.py, amundsen_application/api/metadata/v0.py, amundsen_application/api/preview/v0.py, amundsen_application/api/search/v0.py, amundsen_application/api/v0.py, amundsen_application/static/js/ducks/api/announcements/v0.ts, amundsen_application/static/js/ducks/api/feedback/v0.ts, amundsen_application/static/js/ducks/api/metadata/v0.ts, amundsen_application/static/js/ducks/api/preview/v0.ts, amundsen_application/static/js/ducks/api/search/v0.ts, tests/unit/api/mail/test_v0.py, tests/unit/api/metadata/test_v0.py, tests/unit/api/search/test_v0.py
**Overview**
This PR completes a previously incomplete reorganization of our blueprints for different pieces of our API, and adds the version to the API path to make it possible to call different API versions.
**Summary of Changes**
1. Our logic for `announcements` and `preview` were the last pieces that needed to be moved to their own Flask blueprints for consistency. 
2. The version (`v0`) has been appended to the url prefixes for each blueprint. This will allow the React application to call specific versions of apis in the future. Note that the `v0` paths are hardcoded in our application logic in `ducks/api`, but the intent is to introduce an application config variable for these when we start supporting different API versions.
=> Cleanup blueprints for API version separation

amundsen_application/static/js/components/TableDetail/styles.scss
This PR completes a quick design request to make the table detail title bold.
=> Tweak .detail-header styles

amundsen_application/static/config/config-default.ts, amundsen_application/static/config/config.types.ts, amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx
- Added 'isBeta' configs which adds a "(BETA)" label in each section
=> Renamed configs for the table profile and table lineage sections

amundsen_application/static/js/components/common/Tabs/index.tsx, amundsen_application/static/js/components/common/Tabs/styles.scss
- Leverages existing bootstrap-react tab components
- Currently there are plans to use this in the search and user profile pages.
=> Added a styled tab component

amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/EntityCard/styles.scss, amundsen_application/static/js/components/common/Feedback/FeedbackForm/styles.scss, amundsen_application/static/js/components/common/Feedback/styles.scss
- Fixed panel borders/shadow/padding
- Removed double margin from .table-details > .row
=> Minor visual changes

docs/installation.md
The `sample_data_loader.py` adds the test data based on the CSV sample data files available in the [amundsendatabuilder](https://github.com/lyft/amundsendatabuilder/tree/master/example/sample_data)
=> Update docs based on the modified test script

amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/index.tsx
Periodic update to ensure we don't have a massive merge conflict at the end.
=> Merge 'master' into 'feature/people'

amundsen_application/api/search/v0.py, amundsen_application/static/js/ducks/search/api/v0.ts, tests/unit/api/search/test_v0.py
- User search just returns mocked data
=> Updated search APIs to support multiple types

amundsen_application/api/search/v0.py, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/types.ts, tests/unit/api/metadata/test_v0.py, tests/unit/api/search/test_v0.py
- Conditionally hide the timestamp when not present
=> changed 'last_updated' to 'last_updated_epoch'

amundsen_application/static/css/_buttons-default.scss, amundsen_application/static/css/_icons.scss, amundsen_application/static/css/_list-group-item.scss, amundsen_application/static/css/_popovers.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/css/styles.scss, amundsen_application/static/js/components/AnnouncementPage/styles.scss, amundsen_application/static/js/components/Footer/styles.scss, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/SearchPage/SearchBar/index.tsx, amundsen_application/static/js/components/SearchPage/SearchBar/styles.scss, amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/styles.scss, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/Tags/TagInfo/styles.scss, amundsen_application/static/js/components/Tags/TagInput/styles.scss, amundsen_application/static/js/components/common/ConfirmDeleteButton/styles.scss, amundsen_application/static/js/components/common/EditableText/styles.scss, amundsen_application/static/js/components/common/EntityCard/EntityCardSection/styles.scss, amundsen_application/static/js/components/common/Feedback/FeedbackForm/styles.scss, amundsen_application/static/js/components/common/Feedback/styles.scss, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/styles.scss, amundsen_application/static/js/components/common/Tabs/styles.scss
- Added sizes for standard .btn (32px) and .btn-lg (48px)
- Colors - rework of gray, text, and button colors
- Search Bar - Added placeholder color, focus highlighting, enlarged in wide screens
- Tags - TagInput and TagInfo updated according to mocks
=> Design Overhaul pt2

amundsen_application/api/metadata/v0.py, amundsen_application/config.py
This PR implements the feature discussed under https://github.com/lyft/amundsenfrontendlibrary/issues/68
@danwom @jinhyukchang
=> Configurable popular table count via Flask config

amundsen_application/api/__init__.py, docs/installation.md
- fix installation requirements path to `requirements3.txt`
- fix favicon path in `amundsen_application/api/__init__.py` to refer correctly to static ressource
=> update installation.md & favicon path

amundsen_application/api/metadata/v0.py, amundsen_application/api/search/v0.py, amundsen_application/api/utils/request_utils.py
Created a utility function to abstract away the logic that switches between backend clients and simple API endpoints.
=> Refactor call pattern for switching between clients

docs/installation.md
Added a step in the installation document that states virtualbox also needs to be installed after the docker requirements to allow first command to run properly.
=> Updated installation document 

docs/installation.md
- Updated requirements for install
- Updated the install doc to add public.Dockerfile to fix this error: 
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat ../amundsenfrontendlibrary/Dockerfile: no such file or directory
=> Updated the install doc

README.md, amundsen_application/__init__.py, docker-amundsen-atlas.yml
This is WIP as it seems the amundsen images are not publicly available?
(hence it references some 3rd party at the moment, but those builds are incorrect)
cc: @feng-tao @verdan
=> Create docker-compose with Apache Atlas

docker-amundsen-atlas.yml, docker-amundsen.yml, docs/installation.md
I just published the latest image for 3 repos to dockerhub:
https://cloud.docker.com/repository/docker/photoft/amundsen-frontend
https://cloud.docker.com/repository/docker/photoft/amundsen-metadata
https://cloud.docker.com/repository/docker/photoft/amundsen-search
Update the docker compose script and the install guide
=> Update docker compose script

.github/PULL_REQUEST_TEMPLATE.md
Mostly copied from Apache Airflow, and using the same in metadata repository.
Fixes: https://github.com/lyft/amundsenmetadatalibrary/issues/16
cc: @danwom @feng-tao
=> Adds the PR template for Amundsen frontend

README.md
Adding link to Software Engineering Daily
Previewed the README
- [ x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ x] In case of new functionality, my PR adds documentation that describes how to use it.
- [ x] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)
- [ x] I have …
=> Adding link to Software Eng Daily podcast to README

amundsen_application/static/css/_list-group-item.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/styles.scss
- Gray color scale shifted lighter, creates a softer feel
- Blue theme changed to cyan
Visual check
- [x ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
=> Modiefied Color Theme

docs/configuration.md
=> Minor doc formatting (ci skip)

amundsen_application/api/mail/v0.py, amundsen_application/base/base_mail_client.py, amundsen_application/static/css/_buttons-default.scss, amundsen_application/static/jest.config.js, amundsen_application/static/js/components/Feedback/FeedbackForm/BugReportFeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/BugReportFeedbackForm/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RatingFeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RatingFeedbackForm/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RequestFeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RequestFeedbackForm/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/styles.scss, amundsen_application/static/js/components/Feedback/FeedbackForm/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/constants.ts, amundsen_application/static/js/components/Feedback/index.tsx, amundsen_application/static/js/components/Feedback/styles.scss, amundsen_application/static/js/components/Feedback/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/types.ts, amundsen_application/static/js/ducks/feedback/api/v0.ts, amundsen_application/static/js/ducks/feedback/reducer.ts, amundsen_application/static/js/ducks/feedback/sagas.ts, tests/unit/api/mail/test_v0.py
1. `BugReportFeedbackForm` and `RequestFeedbackForm` have been updated to take a subject. `RatingFeedbackForm` was updated for minor visual inconsistencies.
<p float='left'>
</div>
2. A `constants` file was added for hardcoded text for `Feedback` and its nested components.
3. Discovered that we were not correctly handling failures of feedback requests -- updated relevant code in `ducks/feedback` and `FeedbackForm` to correctly propagate errors to the application and display a failure message.
1. Updated `base_mail_client.send_email()` abstraction to also support dictionary of form data. For Lyft's new use case it will be best to send the form data from the feedback forms so we can execute some extra logic based on those values. 
2. Updated the feedback send mail request to also pass the …
=> Feedback Component & MailClient Improvements

.travis.yml
I followed the examples here to hookup code coverage on our code: https://github.com/codecov/example-typescript
https://github.com/codecov/codecov-python#configuration
It **looks** like it works correctly. 
1. When I had JS only configured after the first commit, codecov reported the 41% coverage which is correct for our JS code.
2. When I configured python, codecov temporarily reported 73% coverage (our current python coverage) after the python tests finished first.
3. Once the JS tests finished coverage dropped to 51%, I guess the total coverage for the repo. It would be nice to see the two separately but I see value in just having one number for the total code coverage regardless of language.
No diff is generated because this is the first report. My plan is to merge and see what …
=> [WIP] Codecov Exploration

amundsen_application/api/metadata/v0.py, amundsen_application/api/search/v0.py, amundsen_application/api/utils/request_utils.py, amundsen_application/api/v0.py, amundsen_application/config.py, setup.py
For now, the request headers can be set using config variable. This PR updates the mechanism to allow to pass a function to generate headers dynamically based on the app state by passing in the current app. This will help pass the authorization headers across different microservices i.e., JWT tokens. 
Also, refactored the code and put the call and headers within the single place in the codebase. 
No tests are added as this simply refactors the code a bit. 
No documentation needed. Added the docstring for newly added functions. 
- All the public python …
=> Implements new utility methods to handle the request headers

amundsen_application/api/utils/request_utils.py
Totally missed this before, we should pass headers also in case of requests. This is important when passing JWT across different microservices.
Not needed
Not required
=> Add `headers` in case of default request client

amundsen_application/models/user.py, tests/unit/models/test_user.py
Based on our current production ready features, all User objects must have a `display_name`. We also have a future feature that will require `user_id`. This PR modifies some logic in the User model to ensure that those features work:
1. `display_name` and `user_id` are not allowed to be `None` on the User object.
2. `email` is required because it is the fallback for the two values that are not allowed to be `None`.
3. Added a helper method to check for `None` and empty string equivalents.
4. Updated the ValidationError messages to provide more helpful information about what values our implementation expects.
This PR will the current case where the NavBar Avatar is not rendering correctly because the `display_name` was allowed to be an empty string.
No tests were added because the main …
=> Update User Model

.travis.yml
2nd attempt of https://github.com/lyft/amundsenfrontendlibrary/pull/150
Same as https://github.com/lyft/amundsenfrontendlibrary/pull/150
=> 2nd attempt on Dockerhub CI

setup.py
=> Add python3.6 , python3.7 in package note

setup.py
update pypi version to include: 1. auto docker push; 2. push python suggested version to pypi
=> update pypi version

amundsen_application/static/tsconfig.json
This PR fixes `npm run tsc`, which was error-ing previously.
Addresses [this issue](https://github.com/lyft/amundsenfrontendlibrary/issues/145)
=> Include the js folder in typescript config to fix "npm run tsc"

docs/developer_guide.md
This PR updates the developer guide with a note about `npm run tsc` now that the configuration has been fixed in https://github.com/lyft/amundsenfrontendlibrary/pull/151
This section is not applicable to doc changes.
Updated docs/developer_guide.md
=> Add note about npm run tsc

README.md
=> Add pypi badge to readme

amundsen_application/base/base_superset_preview_client.py, amundsen_application/base/examples/example_superset_preview_client.py, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/types.ts, docs/examples/superset_preview_client.md, tests/unit/api/search/test_v0.py, tests/unit/base/test_superset_preview_client.py
This PR addresses https://github.com/lyft/amundsenfrontendlibrary/issues/69:
1. Created a `base_superset_preview_client` as a starting point for using Superset as the provider for Amundsen's data preview feature.
2. Implemented an `example_superset_preview_client`. Note that this is only an example for getting data from a default table in an instance of Superset, running on localhost with security/auth features disabled. It will not work out-of-the-box in production without more custom logic.
3. Updated the parameters for the data preview feature to include the `database`. The request to Superset's `sql_json` endpoint requires a `database_id`, so we pass the database name for the client to incorporate logic for the potential use case of querying different databases. 
1. Added …
=> Add `base_superset_client` & documentation

amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx
Fixes an issue where nested datatypes returned by the data preview API return an actual JSON object rather than a string. This causes a rendering error the breaks the app.
=> Added a fix for nested JSON data type returned from data preview

amundsen_application/static/js/components/SearchPage/styles.scss
Fixed misaligned search info tooltip button, more info [here](https://jira.lyft.net/browse/DPTOOLS-2255)
N/A
N/A
=> Fixed styling for search info button

amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/NavBar/tests/index.spec.tsx
Added link to home page of Amundsen for the Lyft logo in the nav bar as requested [here](https://jira.lyft.net/browse/DPTOOLS-2044)
N/A
N/A
=> Added link to home on header logo

docker-amundsen.yml
* uses tagged versions of the three Amundsen services
* sets PROXY_ENDPOINT for the elasticsearch container
which _should_ make it JustWork(tm) with docker-engine
based setups. NOTE this requires the 1.0.2 version of the
search service container
* similarly sets PROXY_HOST for neo4j
No changes to tests. We don't have tests for docker-compose (though I think I saw someone building tests for container integrations as well)
**NOTE** This PR relies on that the Amundsen search service container v 1.0.2 gets tagged and pushed to DockerHub. Do not merge before that has been pushed! 
No Documentation changes. I think as followup PRs we can improve docs though - e.g. document `PROXY_HOST` etc. environment vars.
- In case you …
=> docker-amundsen.yml pegging to tagged versions

amundsen_application/static/js/components/common/AvatarLabel/styles.scss
Fixed AvatarLavels overflow issue in the EntityCard as described [here](https://jira.lyft.net/browse/DPTOOLS-2247)
=> Fixed AvatarLabels in EntityCard overflow

docker-amundsen.yml
We use test as the password in databuilder sample loader(https://github.com/lyft/amundsendatabuilder/blob/master/example/scripts/sample_data_loader.py#L42).
=>  Change neo4j password to test

amundsen_application/static/css/_avatars.scss, amundsen_application/static/css/styles.scss, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/styles.scss
Change z index of frequent user avatars so the most frequent user is at the top
N/A
N/A
=> Reverse frequent user order positioning

docs/authentication/oidc.md, docs/configuration.md
This PR adds the documentation and explains the steps needed to configure OIDC in Amundsen's each microservice. 
Not test needed, as this is a documentation change. 
This adds the documentation about adding the authentication support. 
=> Documents as how to setup OIDC authentication in Amundsen

README.md
Adding link to YouTube video from Strata SF.
Previewed the content
- [ x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
=> Adding link to YouTube video from Strata SF

docker-amundsen.yml, docs/installation.md
Update quick start to just use docker-compose and not docker-machine and fix setting the default password in neo4j so it can be run easier.
No tests committed, but I ran through the setup on a machine with nothing to start and it worked out of the box.
Updated the installation.md file.
=> Update quick start and docker-compose

docs/authentication/oidc.md
This updates the documentation of OIDC support, and explains how to setup the AUTH_USER_METHOD using OIDC provider. 
N/A
This is documentation change. Please refer to summary of this PR.
=> Add the documentation of how to set Auth User Method

README.md
Include ING's kubecon presentation(https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1559072859084400).
=> Update readme.md to include ING's presentation

README.md
Update README.md to amend #176 with video link
Video link timer set to just before Amundsen mention starts
Visual PR Markdown inspection
Yep! README.md
=> Update README.md to amend #176 with video link

docs/installation.md
Updated installation docs to include troubleshooting information.
=> Added troubleshooting instructions

amundsen_application/static/js/components/SearchPage/index.tsx, amundsen_application/static/js/components/SearchPage/tests/index.spec.tsx, amundsen_application/static/js/ducks/search/reducer.ts
Made changes to the search page so that changes to the URL would be reflected in changes to the state of the search page. Two things that were fixed in this process: the back and forward buttons on the search page as well as the home button.
Modified SearchPage test so that SearchPage wrapper expects RouteComponentProps from react router.
N/A
=> Fixed state to match URL changes

amundsen_application/static/js/components/NavBar/styles.scss
Link to the home button in the nav bar wasn't turning purple when hovering, made a quick css change to fix
N/A
N/A
=> Fixed hover color on link to home button

amundsen_application/static/package-lock.json, amundsen_application/static/package.json
This PR upgrades out version of the `axios` library. We opted to do a manual upgrade instead of leveraging the PR from `dependabot` as we're not yet sure how that bot works and noticed more diffs than expected in our `package-lock.json`. 
N/A for upgrading libraries
N/A for upgrading libraries
=> Upgrade axios

amundsen_application/api/metadata/v0.py
Log calls to the update_bookmark API
=> Added logging to update bookmark API

docs/installation.md
=> Fixed typo in installation instructions

amundsen_application/static/js/ducks/allTags/api/tests/index.spec.ts, amundsen_application/static/js/ducks/allTags/api/v0.ts, amundsen_application/static/js/ducks/announcements/api/tests/index.spec.ts, amundsen_application/static/js/ducks/announcements/api/v0.ts, amundsen_application/static/js/ducks/bookmark/reducer.ts, amundsen_application/static/js/ducks/bookmark/sagas.ts, amundsen_application/static/js/ducks/bookmark/tests/index.spec.ts, amundsen_application/static/js/ducks/bookmark/types.ts, amundsen_application/static/js/ducks/popularTables/api/v0.ts, amundsen_application/static/js/ducks/search/api/v0.ts, amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/types.ts, amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/owners/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/owners/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/tags/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/tags/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/types.ts, amundsen_application/static/js/ducks/user/api/v0.ts, amundsen_application/static/js/ducks/user/reducer.ts, amundsen_application/static/js/ducks/user/sagas.ts, amundsen_application/static/js/ducks/user/types.ts, amundsen_application/static/js/interfaces/Resources.ts
1. Consistent names for our `AxiosResponse` data types, especially ones that would not conflict with our action types that are named `SomethingResponse`. I've chosen the naming `SomethingAPI`.
2. There were some leftover cases in `ducks/tableMetadata` that were still passing the action to the api call. Instead we want to pass in explicit parameters to help decouple the logic in that file from our actions and their types. 
**_Worthy Mention_**: The `call()` method from `redux-saga` throws type errors if we try to pass variables that are potentially undefined, such as the optional parameters used for logging like `searchIndex` and `source`. A workaround is documented in the code.
3. Simplified ` getTableQueryParams` which used to take an object that was allowed to be either of type …
=> Cleanup ducks folder: Address a few more inconsistencies.

docker-amundsen.yml, setup.py
We did a refactor on search model. We should bump the version.
=> Bump the search version in docker script

amundsen_application/static/js/config/config-custom.ts, amundsen_application/static/js/config/config-default.ts, amundsen_application/static/js/config/config-types.ts, amundsen_application/static/templates/fragments/google-analytics-loader.html, amundsen_application/static/templates/fragments/google-analytics-post-loader.html, amundsen_application/static/templates/index.html, amundsen_application/static/webpack.common.ts, tests/unit/api/mail/test_v0.py, tests/unit/api/metadata/test_v0.py, tests/unit/api/search/test_v0.py
- Refactored `index.html` to use template fragments that are optionally included
- Disabled google analytics by default
- Added 'test' folder to templates for API tests to use
=> Made google analytics disabled by default

docker-amundsen-atlas.yml
Fix version for docker compose script. The latest version could contain testing RC.
=> Fix version for atlas docker script

README.md
Add a power by section based on https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1561012353146600
=> Add powered by section to readme

amundsen_application/static/jest.config.js, amundsen_application/static/js/ducks/tableMetadata/owners/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/owners/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/owners/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/tags/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/tags/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/tags/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/tests/index.spec.ts, amundsen_application/static/js/ducks/user/tests/index.spec.ts
Merging work from one of my unit test branches into another, PR to master is held until https://github.com/lyft/amundsenfrontendlibrary/pull/201 is merged.
Raised coverage of `ducks` to 75%+
N/A
=> Initial ducks/tableMetadata tests

amundsen_application/api/utils/metadata_utils.py, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/index.tsx, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/styles.scss, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/ducks/tableMetadata/reducer.ts
This PR makes the following changes to features on the `TableDetail` page.
1.  Added a section for the "Data Store" type
2. Updated the styles  regarding the column name and column type that will allow for long column titles to wrap.
3. Updated the table lineage section to only render if the url is neither `null` nor an empty string.
4. Updated the explore sql button to only render if the url is neither `null` nor an empty string.
5. Fixed a regression in the tableMetadata reducer that prevented the failure status code from getting passed back to the application, causing the preview button to be stuck on "Loading". This fixes issue #202 .
N/A. The `TableDetailPage` is currently intentionally uncovered due to an upcoming major refactor. The unit tests for `ducks/tableMetadata` exist in PR …
=> Update TableDetail Page

amundsen_application/api/search/v0.py
Allow users to search `database:$db` with adv search syntax.
=> Add database field for adv search

amundsen_application/static/js/components/SearchPage/SearchBar/constants.ts
We should update the help text along with #228 if we are also supporting 'database' for advanced search syntax.
N/A
N/A
=> Update SearchBar help text

amundsen_application/static/js/components/SearchPage/SearchBar/constants.ts
Reverts lyft/amundsenfrontendlibrary#229
=> Revert "Update SearchBar help text"

docs/roadmap.md
Add a roadmap listing Amundsen's Mission and Vision, what we are currently developing and what we will tackle next. This also include some links to designs and specs.
=> add Roadmap

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/notification_utils.py
Adds a check in so that owners adding/removing themselves won't be notified that they have added themselves
N/A
N/A
=> Prevent Self-Notifications

amundsen_application/api/utils/notification_utils.py
Fixed return statement when recipient list is empty.
N/A
N/A
=> Fixed return for no recipients

local.Dockerfile
This PR add a `local.Dockerfile` which came about as part of the investigation to explore a local development workflow in https://github.com/lyft/amundsen/pull/25. 
Notable differences include:
1. The use of `ARG METADATASERVICE_BASE` and `ARG SEARCHSERVICE_BASE` which is used [here](https://github.com/lyft/amundsen/pull/25/files#diff-60a61f813cfaf16d69be9649a5942a1dR55). I *believe* was needed because the environment variables defined for the container were not taking effect when building the container from a local source, and found that passing the values as `args` seemed to work.
2. The addition of `npm rebuild node-sass`. This will ensure that the appropriate Node bindings for the environment used by `docker-compose` are downloaded. (docker is using Linux so someone on a Mac running …
=> Add a dockerfile for local workflow in umbrella repo

amundsen_application/api/metadata/v0.py, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/tests/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/tests/index.spec.tsx, amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, amundsen_application/static/js/ducks/tableMetadata/api/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/user/api/v0.ts, amundsen_application/static/js/ducks/user/reducer.ts, amundsen_application/static/js/ducks/user/sagas.ts, amundsen_application/static/js/ducks/user/tests/index.spec.ts, amundsen_application/static/js/ducks/user/types.ts
- Added optional logging fields `index` and `source` to the GetUser API.
- Removed mandatory inclusion of `index` and `source` to GetTableData API
- Added tests for Profile Page logging params
- Added logging params to various tests.
=> Add better logging for profile page views

amundsen_application/static/js/components/Feedback/styles.scss, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/constants.ts, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/index.tsx, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/styles.scss, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/ducks/notification/api/tests/index.spec.ts, amundsen_application/static/js/ducks/notification/api/v0.ts, amundsen_application/static/js/ducks/notification/reducer.ts, amundsen_application/static/js/ducks/notification/sagas.ts, amundsen_application/static/js/ducks/notification/types.ts, amundsen_application/static/js/ducks/rootReducer.ts, amundsen_application/static/js/ducks/rootSaga.ts, amundsen_application/static/js/fixtures/globalState.ts
New request information component, pretty much has full functionality (sending a POST, grabbing list of owners, close button), need to work on validation and revealing components
N/A
N/A
=> Request notifications component

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/Footer/styles.scss, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/SearchPage/ResourceSelector/index.tsx, amundsen_application/static/js/components/SearchPage/ResourceSelector/tests/index.spec.tsx, amundsen_application/static/js/components/SearchPage/SearchPanel/index.tsx, amundsen_application/static/js/components/SearchPage/SearchPanel/styles.scss, amundsen_application/static/js/components/SearchPage/SearchPanel/tests/index.spec.tsx, amundsen_application/static/js/components/SearchPage/constants.ts, amundsen_application/static/js/components/SearchPage/index.tsx, amundsen_application/static/js/components/SearchPage/styles.scss, amundsen_application/static/js/components/SearchPage/tests/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/styles.scss
`SearchPage`
- Replaced `TabsComponent` with `SearchPanel` and uses radio buttons
- Removed `SearchBar`
`NavBar`
- Added some placeholder colors
- Added variable for `Navbar` and `Footer` height to be used in `SearchPage` styles.
=> Added new search page layout

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/notification_utils.py, amundsen_application/config.py, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/index.tsx, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/owners/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/owners/tests/index.spec.ts, amundsen_application/static/templates/notifications/notification_added.html, amundsen_application/static/templates/notifications/notification_removed.html, amundsen_application/static/templates/notifications/notification_requested.html, tests/unit/api/metadata/test_v0.py, tests/unit/utils/notification/test_v0.py
Added new copy for adding, removing, and requesting metadata notifications
=> Add, Request, and Remove Email Copy

amundsen_application/api/mail/v0.py, amundsen_application/api/utils/notification_utils.py
Adds action logging to notification endpoint
=> Add notification action logging

amundsen_application/static/js/components/Feedback/index.tsx
Gets rid of some calls that I had used for testing
=> Clean feedback notification

amundsen_application/static/css/styles.scss, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss
Adds user dropdown to access user's profile, will be extended to add link to preferences page later.
=> User dropdown

amundsen_application/static/js/components/TableDetail/index.tsx
=> Hide request if description already exists

amundsen_application/static/js/components/TableDetail/OpenRequestDescription/styles.scss, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/styles.scss
=> fixed open request button, request form styling

amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/index.tsx, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/index.tsx, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/tests/index.spec.tsx
Fixes the request form so that it doesn't persist across multiple different table detail pages. Add ids to dropdowns to stop propType errors 
Added componentWillUnmount test
=> Request form navigation fix, dropdown fix

amundsen_application/static/css/_dropdowns.scss, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/NavBar/tests/index.spec.tsx
This PR updates the UI for the user dropdown/menu list items to bring it slightly closer to what we have in our design docs. Any further updates will be best to complete as part of the redesign. Changes include:
1. Name and email in profile dropdown
2. Less padding around list items and lighter highlight.
Updated `NavBar` tests accordingly.
N/A
=> Bring dropdown UI closer to design

amundsen_application/static/js/ducks/notification/api/tests/index.spec.ts, amundsen_application/static/js/ducks/notification/api/v0.ts, amundsen_application/static/js/ducks/notification/reducer.ts, amundsen_application/static/js/ducks/notification/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/owners/tests/index.spec.ts
Code cleanup in `ducks/notifications` and added tests for actions, reducer, and saga logic.
Added tests for actions, reducer, and saga logic in `ducks/notifications`.
N/A
=> Notifications ducks cleanup + tests

amundsen_application/static/templates/notifications/notification_requested.html
Updated the `notification_requested.html` template to send something more appropriate for the edge case of some options being false.
N/A
N/A
=> Fix template for edge case of empty form

amundsen_application/static/css/_buttons-default.scss, amundsen_application/static/css/_colors.scss, amundsen_application/static/css/_icons.scss, amundsen_application/static/css/_inputs.scss, amundsen_application/static/css/_list-group.scss, amundsen_application/static/css/_pagination.scss, amundsen_application/static/css/_popovers.scss, amundsen_application/static/css/_typography-default.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/css/styles.scss, amundsen_application/static/js/components/AnnouncementPage/styles.scss, amundsen_application/static/js/components/Feedback/FeedbackForm/styles.scss, amundsen_application/static/js/components/Feedback/styles.scss, amundsen_application/static/js/components/Footer/styles.scss, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/SearchPage/SearchPanel/styles.scss, amundsen_application/static/js/components/TableDetail/DataPreviewButton/styles.scss, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/styles.scss, amundsen_application/static/js/components/TableDetail/OwnerEditor/styles.scss, amundsen_application/static/js/components/Tags/TagInfo/styles.scss, amundsen_application/static/js/components/Tags/TagInput/styles.scss, amundsen_application/static/js/components/common/Bookmark/BookmarkIcon/styles.scss, amundsen_application/static/js/components/common/EditableText/styles.scss, amundsen_application/static/js/components/common/EntityCard/EntityCardSection/styles.scss, amundsen_application/static/js/components/common/InfoButton/styles.scss, amundsen_application/static/js/components/common/ResourceListItem/styles.scss, amundsen_application/static/js/components/common/SearchBar/styles.scss, amundsen_application/static/js/components/common/Tabs/styles.scss
- Added color palette
- Replaced references to $gray-base, $gray-dark, etc with purpose driven variables (e.g. $tag-bg, $tag-bg-hover, $icon-bg, ...)
- Renamed $text-dark, $text-medium with $text-primary, $text-secondary
=> Implement New color theme

amundsen_application/static/js/ducks/tableMetadata/api/v0.ts
We've had issues with handling AxiosErrors in the case of a failed data preview, and our current implementation overlooked the fact that for some error codes `error.response.data` is not what we expected. In our python code we always return some json data on both success and failure as seen [here](https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/api/preview/v0.py). 
Howevers the way `axios` chooses to handle some errors -- like a `504` -- the response data ends up being a string instead of the object we intended. (mistake here was writing code based on our knowledge of what we thought would happen) 
The fix I've added does some checks based on the documented [axios types](https://github.com/axios/axios/blob/master/index.d.ts). Processing of an `AxiosError` …
=> Update AxiosError handling

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx, amundsen_application/static/js/components/TableDetail/DataPreviewButton/styles.scss, amundsen_application/static/js/components/TableDetail/ExploreButton/index.tsx, amundsen_application/static/js/components/TableDetail/FrequentUsers/index.tsx, amundsen_application/static/js/components/TableDetail/LineageLink/index.tsx, amundsen_application/static/js/components/TableDetail/OwnerEditor/styles.scss, amundsen_application/static/js/components/TableDetail/SourceLink/index.tsx, amundsen_application/static/js/components/TableDetail/WriterLink/index.tsx, amundsen_application/static/js/components/TableDetail/index_old.tsx, amundsen_application/static/js/components/TableDetail/index_v2.tsx, amundsen_application/static/js/components/TableDetail/styles_v2.scss, amundsen_application/static/js/components/common/AvatarLabel/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/styles.scss, amundsen_application/static/js/components/common/AvatarLabel/tests/index.spec.tsx, amundsen_application/static/js/interfaces/TableMetadata.ts
Created components for each section of the TableDetails page and placed them into the v2 layout.
- ExploreButton, LineageLink, WriterLink, SourceLink, FrequentUsers
- DataPreviewButton: added data fetch, use `props` instead of `state`
Will add tests to new components in follow up
=> Create Table Detail Components for V2

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/request_utils.py, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/components/common/EditableText/tests/index.spec.tsx, amundsen_application/static/package-lock.json, amundsen_application/static/package.json, amundsen_application/static/tsconfig.json, setup.py, tests/unit/api/metadata/test_v0.py
Introduced support of Markdown descriptions for tables & columns.
This module changes are intended to render Markdown and to autosize HTMLTextAreaElement on edit (to fit content).
Also dependencies have been updated and build / dev-build scripts have been modified to support run on alternative environments (for instance Win10).
[Related changes at amundsenmetadatalibrary.](https://github.com/lyft/amundsenmetadatalibrary/pull/79)
EditableText element tests have been modified to match changes (nested `<ReactMarkdown/>` tag for table and column descriptions).
Markdown description format demo:
https://rexxars.github.io/react-markdown/
=> Improve table & columns description formatting (#98)

amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/index.tsx, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/styles.scss, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/components/common/EditableText/styles.scss, amundsen_application/static/js/config/config-default.ts, amundsen_application/static/js/config/config-types.ts
- Fixed some issue with React-Markdown adding a <p> element that adds unnecessary space.
- Updated usage of Ref Callbacks to new React.createRefs.
=> Update EditableText component

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/request_utils.py, setup.py
Changed usage of 'json' to 'data' for backwards compatibility with systems that do not support 'json' field in the python request utils.
=> Change 'json' to 'data' field for Python Requests

README.md
Will scroll past GitHub repo folders (specially more handy on small screens like phones/tablets)
Like https://github.com/lyft/amundsendatabuilder/pull/147
=> Link deeper to doc content

docs/developer_guide.md
=> Update developer_guide.md fix broken link

local.Dockerfile, public.Dockerfile
Similar to https://github.com/lyft/amundsensearchlibrary/pull/66
=> Pin Docker to Python 3.7

amundsen_application/static/js/components/common/Bookmark/BookmarkIcon/styles.scss, amundsen_application/static/js/components/common/ResourceListItem/styles.scss
Fixes bookmark misalignment in TableDetails and overflow cutoff in TableListItem.
=> Fix bookmark alignment

amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/EditableSection/styles.scss, amundsen_application/static/js/components/TableDetail/OwnerEditor/index.tsx, amundsen_application/static/js/components/TableDetail/OwnerEditor/styles.scss, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/Tags/TagInfo/styles.scss, amundsen_application/static/js/components/Tags/TagInput/styles.scss, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/components/common/EditableText/styles.scss, amundsen_application/static/js/components/common/EditableText/tests/index.spec.tsx
- EditableSection component has been applied to EditableText, Tags, OwnerEditor
- Style cleanup for related components
=> Table v2 editable sections

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx, amundsen_application/static/js/components/TableDetail/ExploreButton/index.tsx, amundsen_application/static/js/components/TableDetail/LineageLink/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/config/config-default.ts
=> Table detail header cleanup

amundsen_application/static/css/_inputs.scss, amundsen_application/static/css/_layouts.scss, amundsen_application/static/css/_popovers.scss, amundsen_application/static/css/_typography-default.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/css/styles.scss, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/styles.scss, amundsen_application/static/js/components/TableDetail/EditableSection/styles.scss, amundsen_application/static/js/components/TableDetail/WriterLink/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/index.tsx
=> Additional design QA

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/components/common/EditableText/styles.scss, amundsen_application/static/js/components/common/EditableText/tests/index.spec.tsx, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts
- Fixed some styling issues on editable text
- Fixed the editable-text refresh action and state management.
=> Table v2 fix editable text

amundsen_application/static/js/components/TableDetail/OwnerEditor/index.tsx
=> cherry-pick updates from master

amundsen_application/static/js/components/TableDetail/index.tsx
Adds the cluster to the table_detail page.
=> Expose the cluster to table_detail page

setup.py
=> Bump the tagged version to 1.2.0

amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/styles.scss
This was a regression from merging search_v2 into master. 
=> Added 'tooltip' to nested column types. 

amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/styles.scss
=> Added `row` and `()` to possible nested columns

amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/ducks/tableMetadata/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/tests/index.spec.ts
The data preview reducer now checks to see the requested data has the same key as the currently viewed table key. This prevents an issue where preview data is incorrectly shown on a different table.
- All the public python functions and the classes in the PR contain docstrings that explain what it …
=> Fix Data Preview Showing Wrong Data

amundsen_application/static/js/components/TableDetail/index.tsx
=> Switch the position between preview and explore button

amundsen_application/__init__.py, amundsen_application/config.py, setup.py
In order to have the proper monitoring in place, based on the internal requirements it would be much easier to have a configurable configuration file for logging. 
Following is the example:
```
[loggers]
keys=root,amundsenmetadata,werkzeug
[handlers]
keys=consoleHandler
[formatters]
keys=amundsenFormatter
[logger_root]
level=DEBUG
handlers=consoleHandler
[logger_werkzeug]
level=DEBUG
handlers=consoleHandler
qualname=werkzeug
propagate=0
[logger_amundsenmetadata]
level=DEBUG
handlers=consoleHandler
qualname=amundsenmetadata
propagate=0
[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=amundsenFormatter
args=(sys.stdout,)
[formatter_amundsenFormatter]
format=%(asctime)s.%(msecs)03d [%(levelname)s][%(name)s] %(module)s.%(funcName)s:%(lineno)d (%(process)d:%(threadName)s) - …
```
=> Implements the functionality to customize the logging - Same as Metadata Service

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/SearchPage/SearchFilter/styles.scss, amundsen_application/static/js/components/SearchPage/SearchPanel/styles.scss, amundsen_application/static/js/config/config-default.ts, setup.cfg
This PR fixes 2 out 6 remaining tasks for improving the search experience:
1. Change "Type" to "Source", this was requested by our users as a more intuitive phrase
2. The `SearchPanel` was increasing in width when we added the `InputFilter`. The current css changes prevent that from happening. `SearchPanel` should now have the same width when toggling back and forth between "People" and "Datasets"
N/A
N/A
=> Filter UI Improvements: Part 1

.editorconfig, local.Dockerfile, public.Dockerfile
- Update node version for Dockerfiles to Node 12
- Add .editorconfig settings
=> Update dockerfiles and .editorconfig

amundsen_application/api/mail/v0.py, amundsen_application/api/utils/notification_utils.py, amundsen_application/base/base_mail_client.py, amundsen_application/base/examples/example_mail_client.py, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/config/config-types.ts, tests/unit/utils/notification/test_utils.py
- "Request Description" link visibility fix
- MailClient implementation example
- API incompatibilities fixes
No tests were added or modified for now.
No documentation added for now.
closes https://github.com/lyft/amundsen/issues/211
=> Amundsen Notifications functionality improvements

amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/tests/index.spec.tsx, amundsen_application/static/js/index.tsx
- Fix inline search results on Table Details page not loading new data
- Added page load logging to inline search results
=> Refactor code around TableDetail page loading

local.Dockerfile
Fixing the local docker build.
No unit tests added or modified.
No documentation modified.
- [ x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [ x] PR includes a summary of changes, including screenshots of any UI changes. 
- [ x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x ] In case of new functionality, my PR adds documentation that describes how to use it.
- All the public python functions and the classes in the …
=> Changing filename from requirements3 to requirements

amundsen_application/static/js/components/HomePage/index.tsx, amundsen_application/static/js/components/HomePage/styles.scss, amundsen_application/static/js/components/common/Breadcrumb/index.tsx, amundsen_application/static/js/components/common/InfoButton/index.tsx, amundsen_application/static/js/components/common/InfoButton/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/index.tsx, amundsen_application/static/js/components/common/SearchBar/tests/index.spec.tsx, amundsen_application/static/js/ducks/rootSaga.ts, amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/types.ts, amundsen_application/static/js/utils/navigation-utils.ts
This PR introduces a variety fo cleanup changes:
1. Add a Breadcrumb on HomePage that makes filters discoverable
2. updateSearchUrl` allows for navigation to just `/search`. If there is no search term or filters in the `searchParams` we now go to `/search`. I think this was the best place to fix a weird state the url would get into when someone used filters with no search term, then cleared all the filters. 
3. Allow for `InfoButton` to use SanitizedHTML. This was because product requested specfic formatting in the tooltips.
4. Not requiring the search term for search bar submit created some edge case issues. Specifically if someone deleted their search term in favor of entering filters but didnt hit enter, that search term would still apply but the UI  did not reflect that the search …
=> Update search flow (some more)

amundsen_application/static/js/components/TableDetail/index.tsx
Fix an issue where we were requesting the same table data as before.
=> Fix the inline search bar reload on a table details page

README.md
=> Update required python version in readme

amundsen_application/static/package-lock.json, amundsen_application/static/package.json
=> Update node-sass to fix security issue

amundsen_application/static/js/components/TableDetail/ExploreButton/index.tsx, amundsen_application/static/js/components/TableDetail/ExploreButton/tests/index.spec.tsx, amundsen_application/static/js/config/config-utils.ts, amundsen_application/static/js/config/tests/index.spec.ts
=> Hide the 'explore' button when not enabled for a particular database

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/TableDetail/OwnerEditor/styles.scss, amundsen_application/static/js/components/TableDetail/WatermarkLabel/styles.scss
- Adds breakpoints at 1200px and 1440px to shrink the left panel.
- The two sub-columns now share the space equally.
=> Adds some responsiveness to table detail layouts

amundsen_application/api/dashboard/v0.py, amundsen_application/static/css/_layouts.scss, amundsen_application/static/css/_list-group.scss, amundsen_application/static/js/components/DashboardPage/ChartList/index.tsx, amundsen_application/static/js/components/DashboardPage/ChartList/styles.scss, amundsen_application/static/js/components/DashboardPage/QueryList/index.tsx, amundsen_application/static/js/components/DashboardPage/QueryList/styles.scss, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.tsx
Added basic versions of the chart and query component. Since this actively designed, these are mostly placeholders.
=> Add chart and query component to dashboard page

amundsen_application/proxy/issue_tracker_clients/jira_client.py, amundsen_application/static/js/components/TableDetail/ReportTableIssue/index.tsx, amundsen_application/static/js/components/TableDetail/ReportTableIssue/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/TableIssues/index.tsx, amundsen_application/static/js/components/TableDetail/TableIssues/styles.scss, amundsen_application/static/js/components/TableDetail/TableIssues/tests/index.spec.tsx, tests/unit/issue_tracker_clients/test_jira_client.py
This PR:
1. Updates the jira issue query to use exact match on the full `Table Key: ....` that we provide. This fixes an issue where unrelated JIRA issues were being displayed due to fuzzy matching.
2. Update the `TableIssue` component to show the `LoadingSpinner` instead of `ReportTableIssue`. With the updated design, it's cleaner for the whole section to be replaced with the `LoadingSpinner` as oppose to just the `Report Issue` text which led also led to a misaligned spinner.
Updated tests to reflect changes.
N/A but big fix can be called out in next patch release. …
=> Update JIRA Issue query + TableIssue UI

amundsen_application/static/js/components/Footer/index.tsx, amundsen_application/static/js/components/Footer/tests/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, docs/configuration.md, docs/examples/superset_preview_client.md, setup.py
This PR addresses two issues highlighted by the open source community this week.
1. Added/updated explicit documentation about python entry points. https://github.com/lyft/amundsen/issues/358
2. Fix and issue where `Footer` causes the app to crash before data is ingested during the quickstart. We were attempting logic on an undefined value. https://github.com/lyft/amundsen/issues/359
Updated `Footer` tests.
Updated configuration docs. 
=> Update doc &  fix Footer

amundsen_application/api/utils/search_utils.py
The effect is that if `badges` are configured as a filter category they will be supported with the change made here: https://github.com/lyft/amundsensearchlibrary/pull/94
N/A
Will call out in release notes for future release. 
=> Add badges as supported field

requirements.txt
Updates the version of amundsen common package
=> Bump the version of amundsen common

amundsen_application/static/js/components/SearchPage/ResourceSelector/index.tsx, amundsen_application/static/js/components/SearchPage/ResourceSelector/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/index.tsx
This PR updates the order of People & Dashboards across the search UI according to our designs. 
Updated relevant test.
N/A
=> Switch order of People & Dashboards across search UI

amundsen_application/static/js/components/DashboardPage/index.tsx
Add count to dashboard right panel tabs
No logic has changed. 
N/A
=> Add count to dashboard right panel tabs

amundsen_application/api/metadata/v0.py, amundsen_application/static/js/components/DashboardPage/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/ducks/dashboard/api/v0.ts, amundsen_application/static/js/ducks/dashboard/sagas.ts, amundsen_application/static/js/ducks/user/api/v0.ts, amundsen_application/static/js/ducks/user/reducer.ts, amundsen_application/static/js/ducks/user/tests/index.spec.ts, amundsen_application/static/js/ducks/user/types.ts, amundsen_application/static/js/utils/logUtils.ts, amundsen_application/static/js/utils/tests/index.spec.ts
This PR completes logging support that we require before our beta test:
1. Update the method name for getting dashboard metadata, which will result in a less ambiguous name in our logs.
2. Separated the logic for processing the `source` & `index` logging params into a utility method as this will be reused on every resource detail page. Updated usages accordingly.
3. Added support to pass dashboard page logging params to the endpoint to be logged appropriately.
Updated tests to reflect changes.
N/A
- All the public python functions and the classes in the …
=> Dashboard Logging Updates

amundsen_application/static/css/_icons.scss, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/FilterSection/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/InputFilter/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx, amundsen_application/static/js/index.tsx, amundsen_application/static/templates/index.html
- Updates resource icons with background image approach
Accessibility improvements:
- Adds a main landmark to the application
- Adds labels to filter inputs
- Adds language to the html tag and some other missing meta tags (to complete)
As mentioned in https://jira.lyft.net/browse/AMD-1056, the current implementation of our icon images is based on inserting content into image tags. This method is hacky and not widely supported, so we wanted to use a better way.
In this PR, I propose a solution based on background images, swapping the previous image tags with fixed-size spans that use the same classes to set their background image. This approach is widely used and battle tested, although **I would recommend moving into a different solution in the future: inserting the SVG icons directly.** …
=> Fixes DataSource or Dashboard Icons not rendering on Firefox

amundsen_application/static/css/_icons.scss, amundsen_application/static/js/components/ProfilePage/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx
Fixes the User Search icon on the typeahead results
Updated tests
=> Fixes the user search icon

amundsen_application/static/js/components/DashboardPage/ShimmeringDashboardLoader/index.tsx, amundsen_application/static/js/components/DashboardPage/ShimmeringDashboardLoader/styles.scss
Updates the shimmering loading animation to mimic that on LPL
Tested manually
=> Animation mimics LPL animation for shimmering loader

amundsen_application/static/js/components/TableDetail/TableIssues/styles.scss
Changed Border and font of 'Open Issues' to match design
No test added or modified
NA
=> [AMD-1385] Changed 'Issue' border to match design

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/TableDetail/TableIssues/styles.scss
- Defined new variable $stroke-variable
- Used predefined variable sin stylesheet of Table Issues Component
=> [AMD-1385] Added and used color from variables file

amundsen_application/models/user.py
Passing `app.config['GET_PROFILE_URL']` into the `user_data` yields a json not serializable error in some environments. The source of this bug in in amundsencommon: https://github.com/lyft/amundsencommon/pull/36#discussion_r427602371.
To temporarily fix this issue, we are reintroducing some of the previous logic that was removed in 
https://github.com/lyft/amundsenfrontendlibrary/pull/440
We will file a follow up issue on the ideal fix for this case, which is to include `profile_url` when user metadata in ingested, and we can completely remove the `GET_PROFILE_URL` configuration from Amundsen, in favor of generating it on the backend.
N/A, all code added in this PR is intended to be deleted once we complete the follow up ticket.
N/A no functionality added, but we will be documenting the …
=> Update profile url workaround

amundsen_application/static/.babelrc, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/index.tsx, amundsen_application/static/package-lock.json, amundsen_application/static/package.json, amundsen_application/static/webpack.common.ts, amundsen_application/static/webpack.dev.ts
- Optimizes load of lodash
- Adds moment-locales-webpack-plugin to prune included moment locales except 'en'
- Adds BundleAnalyzerPlugin (commented) to analyze bundle sizes
- Updates clean-webpack-plugin
Before:
After:
Ran tests, checked sizes with the bundle analyzer
=> Optimizes JavaScript Bundle

.github/prlint.json
=> chore: add prlint for fe

amundsen_application/config.py, amundsen_application/proxy/issue_tracker_clients/__init__.py, amundsen_application/proxy/issue_tracker_clients/jira_client.py, amundsen_application/static/js/components/TableDetail/TableIssues/styles.scss, tests/unit/issue_tracker_clients/test_jira_client.py
For our feature that supports reporting issues on a table resource via JIRA, we have a request to add a specific label on the tickets to make them easier to find by our customer. This PR adds an `ISSUE_LABELS` configuration, which is a list of strings and will applied on all created tickets.
Additionally, this PR makes some style changes to our UI when there are multiple issues. At some point there must have been some style regression.
_Before (incorrect):_
_After (matches design)_
JIRA client tests were updated accordingly
N/A for this PR but the `ISSUE_LABEL` addition will be mentioned in the next set of release notes.
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party …
=> feat: Configure JIRA Issue Labels

amundsen_application/api/metadata/v0.py, tests/unit/api/metadata/test_v0.py
Adds a new endpoint
Adds API tests
=> feat: Related Dashboards endpoint on Flask app

amundsen_application/static/js/components/DashboardPage/styles.scss, amundsen_application/static/js/components/TableDetail/ExploreButton/index.spec.tsx, amundsen_application/static/js/components/TableDetail/constants.ts, amundsen_application/static/js/components/TableDetail/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/TabsComponent/styles.scss, amundsen_application/static/js/config/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/api/helpers.spec.ts, amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/fixtures/globalState.ts, amundsen_application/static/js/fixtures/metadata/table.ts, amundsen_application/static/js/interfaces/TableMetadata.ts
Adds a related dashboards tab on the Table detail page
Added some basic tests to table detail
Added tests to the helper functions
=> feat: Adds related dashboards tab to the Table detail page

amundsen_application/static/js/components/TableDetail/TableIssues/index.tsx, amundsen_application/static/js/components/TableDetail/TableIssues/styles.scss
For our UI when there are no issues to display, I noticed some more small discrepancies in the `TableIssues` styling:
1. The desired `line-height` to help center the text was not being applied
2. The `Report an Issue` link had a left margin that only needs to be applied when the previous link is rendered.
This PR resolves those styling issues, but in order to do so I also found it easier to restructure the rendering logic. The logic was restructured so that the boolean logic is wrapped into the method that renders each chunk.
**Before:**
_Note:_ Text is slightly vertically off  & `Report an issue` is not aligned properly on the left.
**After:**
_Note:_ Text is vertically centered & `Report an issue` is flush with the left side.
N/A. The testable results of this component have not changed. …
=> style: Resolve unintended discrepancies in TableIssues

amundsen_application/static/js/components/DashboardPage/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/TableDetail/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/index.spec.tsx, amundsen_application/static/js/components/common/BadgeList/index.spec.tsx, amundsen_application/static/js/components/common/Bookmark/BookmarkIcon/index.spec.tsx, amundsen_application/static/js/components/common/Breadcrumb/index.spec.tsx, amundsen_application/static/js/components/common/EditableText/index.spec.tsx, amundsen_application/static/js/components/common/EntityCard/EntityCardSection/index.spec.tsx, amundsen_application/static/js/components/common/EntityCard/index.spec.tsx, amundsen_application/static/js/components/common/Flag/index.spec.tsx, amundsen_application/static/js/components/common/FlashMessage/index.spec.tsx, amundsen_application/static/js/components/common/Inputs/CheckBoxItem/index.spec.tsx, amundsen_application/static/js/components/common/LoadingSpinner/index.spec.tsx, amundsen_application/static/js/components/common/Preloader/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/index.spec.tsx, amundsen_application/static/js/components/common/TabsComponent/index.spec.tsx, amundsen_application/static/js/components/common/TagsList/index.spec.tsx, amundsen_application/static/js/fixtures/metadata/dashboard.ts, amundsen_application/static/js/index.tsx, amundsen_application/static/js/utils/index.spec.ts, amundsen_application/static/js/utils/navigationUtils.ts
Updates the Dashboard Page URL to avoid depending on the query parameters
Flattened some components folder structure, removing /tests folders
Updated tests
=> fix: Updates the Dashboard Page URL

amundsen_application/dashboard_preview/mode_preview.py, tests/unit/dashboard_preview/test_mode_preview.py
Dashboard preview ACL to use `user_id` instead of `email`
Updated unit test. Integration test done.
N/A
=> other : Dashboard preview ACL to use user_id

amundsen_application/static/css/_animations.scss, amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/DashboardPage/styles.scss, amundsen_application/static/js/components/SearchPage/SearchPanel/styles.scss, amundsen_application/static/js/components/SearchPage/styles.scss
Makes the results and the sidebar of the search page scrollable
Adjusts spacing on the dashboard detail and table detail sidebar
=> fix: Fixes scrolling on results pages and pagination

amundsen_application/static/js/components/Footer/index.spec.tsx, amundsen_application/static/js/components/Footer/index.tsx, amundsen_application/static/js/components/Footer/styles.scss, amundsen_application/static/js/components/TableDetail/TableIssues/index.spec.tsx, amundsen_application/static/js/components/TableDetail/TableIssues/index.tsx, amundsen_application/static/js/components/TableDetail/TableIssues/styles.scss, amundsen_application/static/package.json
Adds a Shimmer loader on the Table Issues and Footer
Updates tests
=> feat: Adds Shimmer loader to the Table Issues and Footer

amundsen_application/static/css/_avatars.scss, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/ProfilePage/constants.ts, amundsen_application/static/js/components/ProfilePage/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/styles.scss, amundsen_application/static/js/components/TableDetail/FrequentUsers/index.tsx, amundsen_application/static/js/components/TableDetail/FrequentUsers/styles.scss
Updates Avatar to have a shimmering circle while loading
Updates the header of the Profile page to have a shimmering loader while loading
Updated tests
=> feat: Update Avatar and Profile Page Loading State

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/Tags/TagInfo/styles.scss, amundsen_application/static/js/components/common/ShimmeringTagListLoader/index.spec.tsx, amundsen_application/static/js/components/common/ShimmeringTagListLoader/index.tsx, amundsen_application/static/js/components/common/ShimmeringTagListLoader/styles.scss, amundsen_application/static/js/components/common/TagsList/index.spec.tsx, amundsen_application/static/js/components/common/TagsList/index.tsx, amundsen_application/static/package-lock.json, amundsen_application/static/package.json
Adds a TagList shimmer loader component
Adds it to our TagList component
Updated tests
=> feat: Update TagList Loading State with a shimmer loader

amundsen_application/static/css/_typography-default.scss, amundsen_application/static/js/components/AnnouncementPage/index.tsx, amundsen_application/static/js/components/HomePage/index.tsx, amundsen_application/static/js/components/SearchPage/ResourceSelector/index.spec.tsx, amundsen_application/static/js/components/SearchPage/ResourceSelector/index.tsx, amundsen_application/static/js/components/SearchPage/SearchPanel/styles.scss, amundsen_application/static/js/components/SearchPage/constants.ts, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/index.tsx, amundsen_application/static/js/components/common/PopularTables/index.spec.tsx, amundsen_application/static/js/components/common/PopularTables/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/index.tsx, amundsen_application/static/js/components/common/SearchBar/constants.ts
Adds some heading tags on titles around the application
Updated tests
=> fix: Updates the markup of some titles

amundsen_application/static/css/_animations.scss, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/SearchPage/ResourceSelector/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/SearchItem/index.tsx, amundsen_application/static/js/components/common/ShimmeringTagListLoader/styles.scss
Removed the beta flag for dashboards.
N/A. No tests need to be removed as they were never added for this temporary logic.
N/A
=> fix: Remove beta flag for dashboard UI

.travis.yml
The latest attempt at a release has been failing, even though the master for the most recent commit passes. In the [raw log](https://api.travis-ci.com/v3/job/354590611/log.txt) for the travis build I found the following error: `error: [Errno 11] write could not complete without blocking`.
Searching this error led to https://github.com/travis-ci/travis-ci/issues/8982. This PR tries out the solution from that discussion. 
If this does not help fix the issue, this change will be reverted.
N/A
N/A
- All the public python functions and the classes in the PR …
=> fix: Update travis.yml

.travis.yml
Trying fix from #498 and #499 on the `before_deploy` step. While only the python section is failing, it is only failing when trying to deploy to pypi, so perhaps this is what is needed for the fix to take effect.
N/A
N/A
=> fix: Try fix for pypi build on before_deploy step

amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/common/SearchBar/index.tsx
Added max-width style property with 560px value to /static/js/components/NavBar/styles.scss.
No tests added.
No docs added.
=> fix: added max-width style property with 560px value

amundsen_application/static/package.json
fix the license for package.json based on foundation feedback.
=> chore: fix license for package.json

amundsen_application/static/js/components/TableDetail/DataPreviewButton/constants.ts, amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx
Limit the max length of preview column for display
=> fix: Limit max char to display for preview column

amundsen_application/static/css/_layouts.scss
This PR fixes some of the layout issues we have observed recently, such as https://github.com/lyft/amundsen/issues/575
There were some updates made to layout a few weeks ago as part of https://github.com/lyft/amundsenfrontendlibrary/commit/a87354bda52f5151d8785f4a0d7023a51e215df2, in order to try to enforce a better horizontal alignment of metadata sections that appear in columns. However not only did those styles cause layout issues on skinnier screens, but our new design guidance for the layout in the left panel no longer includes the need to force the minimum height or horizontal alignment of metadata section headers.
N/A
N/A
- In case you are adding a dependency, check if the license complies with the [ASF 3rd …
=> fix: Fix layout

amundsen_application/static/js/components/Tags/TagInfo/index.spec.tsx
This is a test of `mapDispatchToProps` that provides slightly more value than many current examples. The purpose of this method is to connect a presentational component to Redux in order to fire actions that ultimately trigger API calls. 
Many of our current tests do a bare minimum check, to just verify that the expected property exists and is a function. This example goes further because it verifies the expected property is a function by calling it (test would fail if it wasn't) + verifies that calling it triggers the expected action. 
In the event that `mapDispatchToProps` has extra logic written into it that is worth testing (e.g. boolean of if/elese logic) we could test that too. 
Updating a test to provide example.
N/A
Make sure you have checked **all** steps below to ensure a timely …
=> chore: Update a test

amundsen_application/static/css/_labels.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/ProfilePage/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/Badges/styles.scss, amundsen_application/static/js/components/common/Flag/index.spec.tsx, amundsen_application/static/js/components/common/Flag/index.tsx, amundsen_application/static/js/components/common/Flag/styles.scss, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.tsx, amundsen_application/static/js/config/config-types.ts
Adding behavior for clickable badges, clickable badge functionality PR [here](https://github.com/lyft/amundsenfrontendlibrary/pull/519).
N/A
N/A
=> feat: clickable badge style behavior

amundsen_application/static/js/components/BrowsePage/tests/index.spec.tsx, amundsen_application/static/js/ducks/search/filters/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/utilMethods.ts, amundsen_application/static/package.json
Removes unnecessary ESLint warning rule
Fixes no-use-before-define issues and removes ESLint warning
Tests passing, one updated.
=> chore: Fixes small issues and removes its ESLint warnings

amundsen_application/static/js/components/HomePage/index.spec.tsx, amundsen_application/static/js/components/Tags/TagInput/index.tsx, amundsen_application/static/package.json
Fixes issues related to the [no-unused-expressions rule](https://eslint.org/docs/2.0.0/rules/no-unused-expressions) of ESLint
Removes the rule warning (now it will trigger an error)
Updated one test
=> chore: Fixes issues with no-unused-expressions ESLint rule

amundsen_application/static/js/components/AnnouncementPage/index.tsx, amundsen_application/static/js/components/common/Announcements/index.spec.tsx, amundsen_application/static/js/components/common/Announcements/index.tsx, amundsen_application/static/js/ducks/announcements/api/index.spec.ts, amundsen_application/static/js/ducks/announcements/api/v0.ts, amundsen_application/static/js/ducks/announcements/index.spec.ts, amundsen_application/static/js/ducks/announcements/index.ts, amundsen_application/static/js/ducks/announcements/reducer.ts, amundsen_application/static/js/ducks/announcements/sagas.ts, amundsen_application/static/js/ducks/announcements/types.ts, amundsen_application/static/js/ducks/dashboard/api/api.spec.ts, amundsen_application/static/js/ducks/dashboard/reducer.spec.ts, amundsen_application/static/js/ducks/dashboard/sagas.spec.ts, amundsen_application/static/js/ducks/dashboard/sagas.ts, amundsen_application/static/js/ducks/rootReducer.ts, amundsen_application/static/js/fixtures/globalState.ts
Adds a container for the Announcements block
Modifies redux logic to support error and loading states
Added tests
=> feat: Announcements container and saga, api and reducer modifications

amundsen_application/static/js/components/TableDetail/TableIssues/index.tsx, amundsen_application/static/js/components/common/Card/index.spec.tsx, amundsen_application/static/js/components/common/Card/index.tsx
Adds a Card component
Not styled yet
Includes shimmering loader
Added tests
=> feat: Basic unstyled Card skeleton with shimmer loader

amundsen_application/static/css/_animations.scss, amundsen_application/static/css/_typography-default.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/HomePage/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/common/Badges/styles.scss, amundsen_application/static/js/components/common/Card/index.spec.tsx, amundsen_application/static/js/components/common/Card/index.tsx, amundsen_application/static/js/components/common/Card/styles.scss, amundsen_application/static/js/components/common/ShimmeringTagListLoader/styles.scss
Adds styling to the cards we'll use on announcements
Adds new tests
=> feat: Card Styling for announcements

.travis.yml
Changed repo name to amundsen.io
=> ci: Update repo name in travis file

amundsen_application/static/global.d.ts, amundsen_application/static/js/ducks/bookmark/index.spec.ts, amundsen_application/static/js/ducks/bookmark/sagas.ts, amundsen_application/static/js/ducks/user/index.spec.ts, amundsen_application/static/package-lock.json, amundsen_application/static/package.json
Fixes pending TypeScript issues after running 'npm run tsc'
Updated tests
=> fix: Fixes TypeScript issues with sagas and saga tests

docs/developer_guide.md
Signed-off-by: Dorian Johnson <2020@dorianj.net>
=> docs: describe storybook

setup.py
Updated version for pypi release
N/A
Release notes will be included in the release.
=> chore: Bump version for pypi release.

README.md
we don't use travis any more. Remove that badge.
=> chore: remove travis badge and update doc link

amundsen_application/static/js/components/DashboardPage/ImagePreview/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/QueryListItem/index.tsx, amundsen_application/static/js/components/DashboardPage/index.spec.tsx, amundsen_application/static/js/components/Feedback/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ExploreButton/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ResourceReportsDropdown/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ResourceReportsDropdown/index.tsx, amundsen_application/static/js/components/common/Bookmark/BookmarkIcon/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/SearchItem/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/index.tsx, amundsen_application/static/js/ducks/dashboard/reducer.spec.ts, amundsen_application/static/js/ducks/issue/api/tests/index.spec.ts, amundsen_application/static/js/ducks/lastIndexed/api/v0.ts, amundsen_application/static/js/ducks/search/api/tests/index.spec.ts, amundsen_application/static/js/ducks/search/filters/reducer.spec.ts, amundsen_application/static/js/ducks/search/filters/sagas.spec.ts, amundsen_application/static/js/ducks/search/reducer.spec.ts, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/tests/sagas.spec.ts, amundsen_application/static/js/ducks/tableMetadata/api/helpers.spec.ts, amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/owners/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/tags/api/tests/index.spec.ts, amundsen_application/static/package.json, docs/developer_guide.md
Tried to remove the @typescript-eslint/no-unused-vars warning, got it down by 84, still 100 outstanding issues
Ran tests, updated some
=> chore: Removes 84 unused variables

.github/CODEOWNERS
Adds a Codeowners file with assignations to different team members
=> feat: Testing Codeowners file

amundsen_application/static/css/_typography-default.scss, amundsen_application/static/css/_variables-default.scss
Adjusts line heights to fix cutted titles on table and dashboard page
=> fix: Adjusts line heights to allow for descendants on headlines

amundsen_application/static/css/_icons.scss, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/index.spec.tsx, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/index.tsx, amundsen_application/static/js/components/common/Card/card.story.tsx, amundsen_application/static/js/components/common/FlashMessage/flashMessage.story.tsx, amundsen_application/static/js/components/common/FlashMessage/index.spec.tsx, amundsen_application/static/js/components/common/FlashMessage/index.tsx, amundsen_application/static/js/components/common/FlashMessage/styles.scss, amundsen_application/static/js/components/common/StorySection/index.tsx, amundsen_application/static/js/interfaces/Enums.ts, amundsen_application/static/js/stories/colors.story.tsx, amundsen_application/static/js/stories/typography.story.tsx, amundsen_application/static/js/stories/welcome.story.tsx, amundsen_application/static/package.json
Adds Card story 
Adds Color story
Updates Typography story
Adds StorySection helper component
Updates Welcome story with StorySection block
=> chore: Updating Storybook with Cards, Colors and Typography 

amundsen_application/static/js/components/common/Flag/Flag.story.tsx, amundsen_application/static/js/components/common/Flag/index.tsx
Adds story for the Flag component
=> chore: Completing storybook for Flag component

amundsen_application/static/js/components/common/InfoButton/infoButton.story.tsx, amundsen_application/static/js/components/common/LoadingSpinner/index.tsx, amundsen_application/static/js/components/common/LoadingSpinner/loadingSpinner.story.tsx, amundsen_application/static/js/components/common/ResourceList/index.tsx, amundsen_application/static/js/components/common/SVGIcons/svgIcons.story.tsx
Adds LoadingSpinner story
Adds InfoButton story
=> chore: Adds stories for LoadingSpinner and InfoButton

amundsen_application/static/.betterer.results, amundsen_application/static/js/interfaces/TableMetadata.ts, amundsen_application/static/js/pages/TableDetailPage/ColumnList/index.tsx, amundsen_application/static/js/pages/TableDetailPage/ColumnListItem/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/ColumnListItem/index.tsx, amundsen_application/static/js/pages/TableDetailPage/ColumnListItem/styles.scss, amundsen_application/static/js/pages/TableDetailPage/RequestMetadataForm/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/RequestMetadataForm/index.tsx, amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/index.tsx, amundsen_application/static/package.json
Refactors the Redux connector out of the ColumnListItems
Fixes issue with RequestMetadataForm
Adds optional usage field to ColumnData
Updated tests
=> refactor: Refactors connector out of ColumnLIstItems

.github/workflows/pypipublish.yml, Makefile
Currently the docker push will mutate the latest tag/version docker file. Do the same change as https://github.com/amundsen-io/amundsenmetadatalibrary
=> chore: fix docker push in FE repo

.github/workflows/license.yml, amundsen_application/static/.betterer.results, amundsen_application/static/js/components/common/Alert/alert.story.tsx, amundsen_application/static/js/components/common/Announcements/AnnouncementsList/index.spec.tsx, amundsen_application/static/js/components/common/Announcements/AnnouncementsList/index.tsx, amundsen_application/static/js/components/common/Announcements/index.spec.tsx, amundsen_application/static/js/components/common/Announcements/index.tsx, amundsen_application/static/js/components/common/Badges/index.spec.tsx, amundsen_application/static/js/components/common/Card/card.story.tsx, amundsen_application/static/js/components/common/Card/index.spec.tsx, amundsen_application/static/js/components/common/Card/index.tsx, amundsen_application/static/js/components/common/Flag/Flag.story.tsx, amundsen_application/static/js/components/common/FlashMessage/flashMessage.story.tsx, amundsen_application/static/js/components/common/InfoButton/infoButton.story.tsx, amundsen_application/static/js/components/common/LoadingSpinner/loadingSpinner.story.tsx, amundsen_application/static/js/components/common/OwnerEditor/index.spec.tsx, amundsen_application/static/js/components/common/SVGIcons/AlertIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/index.tsx, amundsen_application/static/js/components/common/SVGIcons/svgIcons.story.tsx, amundsen_application/static/js/components/common/StorySection/index.tsx, amundsen_application/static/js/pages/TableDetailPage/ResourceReportsDropdown/index.tsx, amundsen_application/static/js/pages/TableDetailPage/SourceLink/index.spec.tsx, amundsen_application/static/js/stories/colors.story.tsx, amundsen_application/static/js/stories/typography.story.tsx, amundsen_application/static/js/stories/welcome.story.tsx
=> chore: add license check action

amundsen_application/static/css/_animations.scss, amundsen_application/static/js/components/common/Table/index.spec.tsx, amundsen_application/static/js/components/common/Table/index.tsx, amundsen_application/static/js/components/common/Table/styles.scss, amundsen_application/static/js/components/common/Table/table.story.tsx, amundsen_application/static/js/components/common/Table/testDataBuilder.ts
Adds Empty and Loading States to the Table component
Added tests
Added storybook example:
=> feat: Empty and Loading states for the table

amundsen_application/static/css/_variables-default.scss
Update the line-height to match those on LPL
This change comes from our reported issue with overflow hidden, and it was tracked by the LPL team on this ticket: https://jira.lyft.net/browse/LPL-5316
=> fix: Updates typography line-height to sync with LPLs

amundsen_application/static/css/_typography-default.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/stories/typography.story.tsx
Adds monospace font definition
Adds caption definitions
Updated storybook
=> feat: Adds caption and monospace font definitions

amundsen_application/static/.betterer.results, amundsen_application/static/js/components/common/Table/index.spec.tsx, amundsen_application/static/js/components/common/Table/index.tsx, amundsen_application/static/js/components/common/Table/styles.scss, amundsen_application/static/js/components/common/Table/table.story.tsx, amundsen_application/static/js/components/common/Table/testDataBuilder.ts, amundsen_application/static/package-lock.json
Makes row height configurable
Makes text alignment configurable
Added tests
Added Storybook stories
=> feat: Adds text alignment and row height options to the reusable table

.github/CODEOWNERS
Would like to get notification for FE pr as well :)
=> chore: add Tao to see FE pr

amundsen_application/static/css/_typography-default.scss, amundsen_application/static/js/pages/DashboardPage/QueryListItem/styles.scss
The list was broken (See ss)
Added elevation on hover and padding for the list items
Current:
Updated:
=> fix: Fixes dashboard query list

amundsen_application/static/.betterer.results, amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/pages/TableDetailPage/constants.ts, amundsen_application/static/js/pages/TableDetailPage/index.tsx
Signed-off-by: Tamika Tannis <ttannis@lyft.com>
New design calls for changing the order:
1. Last Updated, Date Range, & Tags on the left
2. Owners & Frequent Users on the right
N/A no functionality has been added or changed.
N/A no functionality has been added or changed.
=> chore: Update order of table metadata on TableDetailPage

amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/constants.ts, amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/index.tsx, amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/styles.scss
Currently Amundsen has dataset, user and dashboard so far. And the heading is fixed to dataset. Change the wording to resource to be more generic. 
=> fix: update search header wording

amundsen_application/static/.betterer.results, amundsen_application/static/js/ducks/search/filters/reducer.ts, amundsen_application/static/js/pages/DashboardPage/index.spec.tsx, amundsen_application/static/js/pages/DashboardPage/index.tsx, amundsen_application/static/js/pages/DashboardPage/styles.scss
Once click search dashboard group, redirect to search filter page instead of external link.
Test locally
=> feat: redirect dashboard group to search filter after clicking

amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/styles.scss, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/styles.scss, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/tests/index.spec.tsx
Based on the UX design feedback, change the order which the dashboard name will get less likely truncated.
=> fix: change dashboard and group order in search result

amundsen_application/static/js/pages/DashboardPage/index.tsx, amundsen_application/static/js/pages/DashboardPage/styles.scss
We redirect the group URL to search filter page in https://github.com/amundsen-io/amundsenfrontendlibrary/pull/655. Per UX design input, add a new button to open group url
=> feat: add a button to open dashboard group

amundsen_application/static/js/config/config-default.ts
All the search filter is singular except groups is not. Rename it to be consistent with terms
=> chore: rename Groups to Group in dashboard search filter

amundsen_application/api/utils/temporary_table.py, amundsen_application/static/js/components/common/BadgeList/index.tsx, amundsen_application/static/js/components/common/Flag/index.tsx, amundsen_application/static/js/config/config-utils.ts, amundsen_application/static/js/interfaces/Resources.ts
Temporary change to accept both types of badges in badge list
N/A
N/A
=> feat: accept new badges

amundsen_application/api/utils/metadata_utils.py, tests/unit/utils/test_metadata_utils.py
different fix per discussion in https://github.com/amundsen-io/amundsenfrontendlibrary/pull/671
=> fix: fix prog desc in fe when no config is provided

tests/unit/api/search/test_v0.py
Fixes issues relating to mypy coverage in https://github.com/amundsen-io/amundsen/issues/703
* Added additional types 
* Refactored assertDictContainsSubset (In Progress)
`tests/unit/api/search/test_v0.py` was modified as requested in the issue. 
N/A
- [] PR passes all tests documented in the [developer …
=> test: Added mypy types to api search unit tests 

amundsen_application/static/css/_variables-default.scss
=> chore: Removes menlo and the -family-monospace variable

amundsen_application/static/js/components/ColumnList/ColumnStats/columnStats.story.tsx, amundsen_application/static/js/components/ColumnList/ColumnStats/index.spec.tsx, amundsen_application/static/js/components/ColumnList/ColumnStats/index.tsx, amundsen_application/static/js/components/ColumnList/ColumnStats/styles.scss, amundsen_application/static/js/components/ColumnList/ColumnStats/testDataBuilder.ts, amundsen_application/static/js/components/ColumnList/index.tsx, amundsen_application/static/js/components/ColumnList/utils.spec.ts, amundsen_application/static/js/components/ColumnList/utils.ts
Tested stats components
Refactors into util function
Added tests
Added stories
=> refactor: Tested and refactored Stats component

amundsen_application/static/.storybook/main.ts, amundsen_application/static/js/components/common/SVGIcons/svgIcons.story.tsx, amundsen_application/static/js/components/common/Table/table.story.tsx, amundsen_application/static/package-lock.json, amundsen_application/static/package.json
Adds knobs to allow for dynamic changes of props from the Storybook UI
=> docs: Adding knobs to Table and SVG Icons

amundsen_application/static/js/components/common/Alert/index.tsx, amundsen_application/static/js/components/common/EntityCard/EntityCardSection/index.spec.tsx, amundsen_application/static/js/components/common/EntityCard/EntityCardSection/index.tsx, amundsen_application/static/js/components/common/InfoButton/index.spec.tsx, amundsen_application/static/js/components/common/InfoButton/index.tsx, amundsen_application/static/js/components/common/InfoButton/infoButton.story.tsx, amundsen_application/static/js/components/common/InfoButton/styles.scss, amundsen_application/static/js/components/common/SVGIcons/AlertIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/DownIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/InformationIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/LeftIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/RightIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/constants.ts, amundsen_application/static/js/components/common/SVGIcons/index.tsx, amundsen_application/static/js/components/common/SVGIcons/svgIcons.story.tsx, amundsen_application/static/js/components/common/SVGIcons/types.ts, amundsen_application/static/js/interfaces/Enums.ts, amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.tsx, amundsen_application/static/package-lock.json, amundsen_application/static/package.json
Adds LeftIcon
Adds Information Icon and uses it within the InfoButton
Updated tests
Added Stories
=> feat: Adds InformationIcon and LeftIcon

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/ColumnList/ColumnStats/index.tsx, amundsen_application/static/js/components/ColumnList/ColumnStats/styles.scss, amundsen_application/static/js/components/common/BadgeList/styles.scss, amundsen_application/static/js/components/common/Table/styles.scss, amundsen_application/static/js/config/config-default.ts, amundsen_application/static/js/config/config-types.ts, amundsen_application/static/js/config/config-utils.ts, amundsen_application/static/js/config/index.spec.ts, amundsen_application/static/js/utils/numberUtils.ts, requirements.txt, tests/unit/api/search/test_v0.py
Signed-off-by: dikshathakur3119 <dikshathakur3119@gmail.com>
Each column may have different column statistics like mean, median, etc. In this PR:
1. Added Numerical separator in the values using [Intl.NumberFormat().format(number)], this format can be configured, default is US format (e.g 1,234,567).
2. Right aligning numbers
3. Monospace font for the numbers
Added test to see if configured number format is used to format column stats.
- All the public python …
=> fix: Align and format column stats (new PR)

amundsen_application/static/.betterer.results, amundsen_application/static/css/_typography-default.scss, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/index.spec.tsx, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/index.tsx, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/styles.scss, amundsen_application/static/js/components/common/PopularTables/index.spec.tsx, amundsen_application/static/js/components/common/PopularTables/index.tsx, amundsen_application/static/js/components/common/PopularTables/styles.scss, amundsen_application/static/js/components/common/Tags/TagsList/index.spec.tsx, amundsen_application/static/js/components/common/Tags/TagsList/index.tsx, amundsen_application/static/js/components/common/Tags/TagsList/styles.scss, amundsen_application/static/js/components/common/Tags/index.tsx, amundsen_application/static/js/stories/typography.story.tsx
Removes title-1 classes from the application
Tweaks spacing on homepage sections
Refactors TagList heading to be more semantic
Adds semantic article tags to homepage sections
Related to https://github.com/amundsen-io/amundsen/issues/646
Updated tests
=> refactor: Removing deprecated title-1 class from Amundsen

setup.py
major release includes new badges work and deprecation of old tag like badges.
N/A
N/A
=> chore: bumped version for new release

amundsen_application/static/.betterer.results, amundsen_application/static/jest.config.js, amundsen_application/static/js/components/Footer/index.tsx, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/index.spec.tsx, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/index.tsx, amundsen_application/static/js/components/common/Card/index.tsx, amundsen_application/static/js/components/common/EditableSection/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.spec.tsx, amundsen_application/static/js/components/common/ScrollTracker/index.tsx, amundsen_application/static/js/components/common/SearchBar/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/index.tsx, amundsen_application/static/js/components/common/Tags/TagInput/index.tsx, amundsen_application/static/js/components/common/Tags/TagsList/index.tsx, amundsen_application/static/js/config/config-utils.ts, amundsen_application/static/js/ducks/announcements/index.ts, amundsen_application/static/js/ducks/lastIndexed/reducer.ts, amundsen_application/static/js/ducks/tags/reducer.ts, amundsen_application/static/js/ducks/user/reducer.ts, amundsen_application/static/js/ducks/utilMethods.ts, amundsen_application/static/js/pages/ProfilePage/index.spec.tsx, amundsen_application/static/js/pages/SearchPage/SearchFilter/FilterSection/index.tsx, amundsen_application/static/js/pages/SearchPage/SearchFilter/index.spec.tsx, amundsen_application/static/js/pages/SearchPage/SearchFilter/index.tsx, amundsen_application/static/js/pages/TableDetailPage/DataPreviewButton/index.tsx, amundsen_application/static/js/pages/TableDetailPage/WatermarkLabel/index.tsx, amundsen_application/static/js/pages/TableDetailPage/index.tsx
ref https://github.com/amundsen-io/amundsen/issues/47
`strictNullChecks` 68 errors -> 34 errors (35 fixes, 1 regression).
This should be all the relatively trivial fixes. The remaining PRs will be a bit tricker, and will be grouped per-topic, rather than big mixes.
no tests modified
n/a
=> chore: finish remaining simple null check typing fixes

amundsen_application/static/js/pages/DashboardPage/index.tsx, amundsen_application/static/js/pages/ProfilePage/index.tsx, amundsen_application/static/js/pages/TableDetailPage/index.tsx
Adds titles to the Detail Page Headers so we can read them when they are hidden with ellipsis
Manually
Nothing here
=> fix: Adding titles to Detail Page headers

amundsen_application/static/js/components/ColumnList/index.tsx
Signed-off-by: hyein <bogo96@kaist.ac.kr>
- fix to display column statics datails.
related issue: amundsen-io/amundsen#814
- test with sample data(databuilder/example/scripts/sample_data_loader.py
=> fix: Fix to display column statics

amundsen_application/static/package-lock.json, amundsen_application/static/package.json, amundsen_application/static/webpack.common.ts
ref: https://github.com/amundsen-io/amundsen/issues/794
Upgrade Webpack from 4 -> 5. Upgrade a few webpack plugin packages to fix deprecation warnings.
There is still one deprecation warning with a plain build:
```
(node:68621) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callbac
k)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
```
This is [fixed in the newest version of `html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin/issues/1523), but it's in alpha and it's a major release, so I suggest just waiting until that comes out and upgrading separately.
There are other errors revealed by `node --trace-deprecation`... I believe that …
=> chore: build: upgrade webpack from 4 to 5

requirements.txt
Reverts amundsen-io/amundsenfrontendlibrary#784
=> fix: Revert "fix: (until they update urllib3) rolling back to v 0.10.15 of responses"

amundsen_application/api/utils/request_utils.py
=> chore: Minor fix in request_utils.py: Show default error msg if none given

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/metadata_utils.py, tests/unit/api/metadata/test_v0.py, tests/unit/utils/test_metadata_utils.py
This error was introduced in https://github.com/amundsen-io/amundsenfrontendlibrary/commit/0b47694ea74cbbef34e03eb45f29643b16a1332a
I do not understand why that changeset passed CI (it shouldn't have), but
once it landed into master it didn't. But regardless, fix
n/a
=> chore: fix test failure

setup.py
Signed-off-by: Dorian Johnson <2020@dorianj.net>
=> chore: bump version from 3.0.0 -> 3.1.0

.github/PULL_REQUEST_TEMPLATE.md, amundsen_application/static/js/pages/DashboardPage/QueryListItem/styles.scss
Adjusts margins on copy button of codebox
Manually
=> fix: Adjusting margin on copy button for codebox

amundsen_application/api/metadata/v0.py, amundsen_application/config.py, tests/unit/api/metadata/test_v0.py
Signed-off-by: Josh Howard <joshthoward@gmail.com>
Added frontend configuration options for personalized popular tables. This PR is related to [PR](https://github.com/amundsen-io/amundsenmetadatalibrary/pull/232). 
This PR adds new configuration options to query the metadata service popular tables endpoint with the current logged in user to obtain personalized responses from the endpoint. 
NA
NA
- [-] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [-] PR includes a summary of changes, including …
=> feat: Added frontend configuration options for personalized popular tables

.github/workflows/monthly_release.yml, setup.cfg
Added a workflow to create a new release every month.
N/A
N/A
=> chore: monthly release action

.github/workflows/monthly_release.yml, setup.cfg
Automated release failing with error: not enough values to unpack (expected 2, got 1)
=> fix: error in automated release

.github/workflows/monthly_release.yml, setup.cfg
=> fix: fix cron to run later today

.github/workflows/monthly_release.yml
Reverts amundsen-io/amundsenfrontendlibrary#867
Oops...
=> fix: Revert "fix: fix cron to run later today" move up again

.github/workflows/monthly_release.yml, setup.cfg
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>
Release action failing with error
error:   cmdline: git checkout "master"
error:   stderr: 'error: pathspec '"master"' did not match any file(s) known to git'
removing var since master is the default according to python-semantic-release docs.
=> fix: removed branch var on release action config

.github/workflows/monthly_release.yml
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>
=> fix: fixed mixed up branches in release action

.github/workflows/monthly_release.yml, setup.cfg
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>
Changed PR title to add chore: so title lint check passes
=> fix: add chore to monthly release PRs

.github/workflows/monthly_release.yml, setup.cfg
=> fix: yaml syntax error

setup.cfg
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>
really hope these are not needed cause DCO still fails
=> fix: removed quotes on commit title and message

public.Dockerfile
This is related with this [PR](https://github.com/amundsen-io/amundsen/pull/858). I also changed this env name in the comments from public.Dockerfile to sync with that.
Since it is in sync with the PR that has already been merged, I think there is no need for testing.
https://github.com/amundsen-io/amundsen/pull/858/files
https://github.com/verdan/flaskoidc/blob/master/flaskoidc/config.py#L15
=> fix: Update env name of oidc secret key from dockerfile

amundsen_application/static/package-lock.json, amundsen_application/static/package.json
Signed-off-by: verdan <verdan.mahmood@gmail.com>
=> Revert "chore: build(deps): bump redux-promise from 0.5.3 to 0.6.0 in /amundsen_application/static"

.dependabot/config.yml
Signed-off-by: Dorian Johnson <2020@dorianj.net>
cc @allisonsuarez @feng-tao 
=> chore: dependabot: change update frequency to monthly

amundsen_application/static/js/config/config-default.ts, amundsen_application/static/js/config/config-types.ts, amundsen_application/static/js/config/config-utils.ts, amundsen_application/static/js/config/index.spec.ts, amundsen_application/static/js/features/NavBar/index.spec.tsx, amundsen_application/static/js/features/NavBar/index.tsx, amundsen_application/static/js/index.tsx
Add style customization points as well as NavBar logo
=> feat: Make NavBar title and DocumentTitle configurable

.github/workflows/publish_release.yml, setup.py
=> chore: update docker publisher new action

amundsen_application/static/js/utils/index.spec.ts, amundsen_application/static/js/utils/stats.ts, docs/application_config.md
Handles JSON parsing errors when failing to parse unique values on table stats
Adds test 
Added test
Updated docs
=> fix: Handles parsing errors when format not expected on distinct values

.github/CODEOWNERS
=> chore: Adding Daniel Won as codeowner on the frontend repository

amundsen_application/static/js/features/ColumnList/ColumnStats/index.tsx, amundsen_application/static/js/features/ColumnList/ColumnStats/styles.scss, amundsen_application/static/js/features/ExpandableUniqueValues/UniqueValuesModal.tsx
Fixes weirdness with stats and unique values formatting
Manually
=> Fix: Normalizes format of stats and unique value labels

.dockerignore, local.Dockerfile, public.Dockerfile
This patch enables docker image users to add their custom config files easily.
Previous `setup.py install` had installed the application to system sites, and files added under `amundsen_application/` by `COPY` or `ADD` had not been recognized.
closes:  https://github.com/amundsen-io/amundsen/issues/190
related: https://github.com/amundsen-io/amundsen/issues/408
=> fix: Make application docker image configurable

amundsen_application/static/.betterer.results, amundsen_application/static/jest.config.js, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/features/ColumnList/ColumnLineage/index.tsx, amundsen_application/static/js/features/ColumnList/ColumnLineage/styles.scss, amundsen_application/static/js/features/ColumnList/ColumnLineageLoader/index.spec.tsx, amundsen_application/static/js/features/ColumnList/ColumnLineageLoader/index.tsx, amundsen_application/static/js/features/ColumnList/ColumnLineageLoader/styles.scss, amundsen_application/static/js/fixtures/metadata/table.ts, amundsen_application/static/js/interfaces/TableMetadata.ts, amundsen_application/static/js/pages/DashboardPage/ShimmeringDashboardLoader/index.tsx, amundsen_application/static/js/pages/DashboardPage/ShimmeringDashboardLoader/styles.scss, amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/index.tsx
General UX polish for lineage features
- Loading state for column lineage
- Hide upstream/downstream tabs when not present
- Added some tests about table detail tabs
=> feat: Table and Column Lineage Polish

.gitignore, amundsen_application/base/base_redash_preview_client.py, amundsen_application/base/examples/example_redash_preview_client.py, docs/examples/redash_preview_client.md, tests/unit/base/test_redash_preview_client.py
Created a new data preview client that leverages Redash to serve data. 
Added additional tests for Redash data preview client.
Added initial documentation, will likely need to update links and references after this PR is merged. Examples for using the client are provided.
=> feat: Add Redash Preview Client

.github/PULL_REQUEST_TEMPLATE.md, README.md
Signed-off-by: Dorian Johnson <2020@dorianj.net>
=> chore: deprecation notice
