amundsen_application/static/config/config-default.ts, amundsen_application/static/config/config.types.ts, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss
This PR adds support for customizable logo in the `NavBar`.  
**Summary of Changes**
1. A `logoPath` option was added to the application configuration, which is `null` by default until we have the design resources for an official Amundsen logo. If a `logoPath` exists, it will render it on the left hand side of the `NavBar`. We do not have any checks/fallbacks for a bad path -- this implementation expects that if a `logoPath` is configured, it is valid.
2. CSS has also been updated accordingly to space the items in `.nav-bar-left`  in the same way they are spaced in `.nav-bar-right`
=> Add support for a logo in the NavBar

amundsen_application/static/css/_popovers.scss, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/components/common/EditableText/styles.scss
- Use "edit" link instead of icon
- "edit" is visible for empty text values and on hover
- textarea appears flush with blackground
-- textarea gets light gradient on de-focus
=> Changed editable-text interaction

docs/installation.md
It is important to install the amundsen data builder before running the test script locally, 
otherwise the imports won't work in the test script.
=> Add the setup line for amundsen data builder

README.md
the link for arch is incorrect.
=> Update the link in the readme

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/Flag/index.tsx, amundsen_application/static/js/components/common/Flag/styles.scss
This PR adds a `Flag` component, which will be needed for upcoming features. The default color is dark text on light gray text. Colors can be customized with css by overriding `color` and `background-color` on the component.
**Examples**
Also noticed the need for css tweak for `.detail-list-header` when testing this.
=> Add re-useable Flag component

amundsen_application/static/css/_buttons-default.scss, amundsen_application/static/js/components/OwnerEditor/index.tsx, amundsen_application/static/js/components/OwnerEditor/styles.scss, amundsen_application/static/js/components/Tags/TagInput/index.tsx, amundsen_application/static/js/components/Tags/TagInput/styles.scss, amundsen_application/static/js/components/common/AvatarLabel/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/styles.scss
In this PR I added 3 new specifications to the button configurations:
1. `btn-icon` for the "flat" buttons that render icons and are gray by default and a brand color on hover.
2. `btn-cancel` and `btn-save` which are currently used in our modal designs.
I've also update the modal in the `TagInput` to match the modal for `OwnerEditor`.
=> Add shared button styles + modify tag modal to match owner modal

amundsen_application/static/js/components/NotFoundPage/index.tsx, amundsen_application/static/js/components/NotFoundPage/styles.scss, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/Breadcrumb/index.tsx, amundsen_application/static/js/components/common/Breadcrumb/styles.scss, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/sagas.ts
1. Update the `Breadcrumb` positioning styles.
2. Added the `Breadcrumb` to `TableDetail` and `NotFoundPage`. `NotFoundPage` breadcrumb says "Home". 
3. Found a minor bug in `ducks`. I needed to pass back the `statusCode` in the `getTableDataWorker` and I also updated some failure cases to return initial pieces of state. I considered putting this in a separate PR in master, but this particular bug only gets revealed when someone types in a bad table detail page url and instead of getting the `NotFoundPage` they will just get a blank page in master. Let me know if there are any strong feelings about the changes in `ducks` going into master instead.
=> Add breadcrumbs + fix to tableData state management

amundsen_application/api/search/v0.py, amundsen_application/static/js/components/SearchPage/SearchBar/index.tsx, amundsen_application/static/js/components/SearchPage/index.tsx, amundsen_application/static/js/components/SearchPage/styles.scss, amundsen_application/static/js/components/common/Tabs/index.tsx, amundsen_application/static/js/components/common/Tabs/styles.scss, amundsen_application/static/js/containers/SearchPage/index.tsx, amundsen_application/static/js/ducks/rootSaga.ts, amundsen_application/static/js/ducks/search/api/v0.ts, amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/types.ts, tests/unit/api/search/test_v0.py
- Added Tabs to search results
- Split `executeSearch` into two actions:
-- `searchAll` will search all resource types. The options allow you to search different page indexes for different resources. This is useful for loading up `&selectedTab=users&tabIndex=5`, since you don't necessarily want to fetch page 5 for all tabs.
-- `searchResource` will run a search on a single resource type. This is primarily used for search pagination.
- The URL should always reflect the current state of the search and can be refreshed or shared to maintain state.
=> Update search to support multiple resource types

amundsen_application/static/css/_buttons-default.scss, amundsen_application/static/css/_icons.scss, amundsen_application/static/css/styles.scss, amundsen_application/static/js/components/AnnouncementPage/styles.scss, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/NotFoundPage/styles.scss, amundsen_application/static/js/components/OwnerEditor/index.tsx, amundsen_application/static/js/components/SearchPage/SearchBar/index.tsx, amundsen_application/static/js/components/SearchPage/SearchBar/styles.scss, amundsen_application/static/js/components/SearchPage/index.tsx, amundsen_application/static/js/components/SearchPage/styles.scss, amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/Tags/TagInfo/index.tsx, amundsen_application/static/js/components/Tags/TagInfo/styles.scss, amundsen_application/static/js/components/Tags/TagInput/index.tsx, amundsen_application/static/js/components/Tags/TagInput/styles.scss, amundsen_application/static/js/components/common/EntityCard/styles.scss, amundsen_application/static/js/components/common/Feedback/FeedbackForm/index.tsx, amundsen_application/static/js/components/common/Feedback/FeedbackForm/styles.scss, amundsen_application/static/js/components/common/Feedback/styles.scss, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/styles.scss, amundsen_application/static/js/index.tsx
Lots of changes, might be easier to look at each commit separately.
Commit 1
- NavBar - Resized to 48px, rework bottom border with box-shadow
- Search Bar - Simplify DOM elements, height 60px, font 24px bold,  narrower in md, lg screens.
Commit 2
- Container top margin at 96, 64, 32px for lg, md, sm screens.
- Search results has 16px top and bottom
Commit 3
- Consolidated buttons classes to: btn-primary btn-default
- Reworked Tag buttons and labels
- Fixed panel border radiuses
Commit 4
- Fixed NavBar active state highlighting
=> Overhaul of UI

requirements3.txt, setup.py
Put all the dependency from requirement3 as install requirement. This is from issue https://github.com/lyft/amundsenfrontendlibrary/issues/79
Also bump FE pypi version.
=> Update setup.py to include requirment3 file

setup.py
I encountered the same issue mentioned by @verdan  in https://github.com/lyft/amundsenfrontendlibrary/pull/82 with a fresh checkout of the repo. The issue seems to be related to using `npm install  --only==prod`.
I don't have much context as @danwom and @ttannis  on this flag. My understanding is to save the build size to reduce page load time? But I don't think page load time is really an issue with the tool.
Per https://github.com/heartsucker/node-deb/issues/15 , it will skip installing those devDependencies listed in package.json.
By removing the `--only==prod`, the `python setup.py install` command works at my local setup.
=> Update setup.py script to fix installation issue

amundsen_application/config.py
In order to have different deployed setups (dev, prod, acc etc.), it would be efficient to set the metadata and search service base from environment variables instead of having separate configuration files.
=> Set the metadata and search base from environment variables

docker-amundsen.yml, docs/installation.md
Add Elasticsearch to docker-compose. Users are able to get demo with search working.
=> Add Elasticsearch service

docker-amundsen.yml
As pointed out by @amweiss, the network info is removed from neo4j container in https://github.com/lyft/amundsenfrontendlibrary/pull/91. We should add it back to make the neo4j container accessible by other container(metadata).
=> Update neo4j docker entry to include the network info

.travis.yml, amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/package.json
This PR fixes a problem that became apparent by https://github.com/lyft/amundsenfrontendlibrary/issues/84, the Travis build was not failing on lint errors. This was because the `tslint` commands were inappropriately using `--force`, which would cause the script to exit without error even if there were lint issues.
**Summary of Changes**
1. Fixed the `tslint` commands to fail if there are errors.
2. Configured `npm run lint` to run as a separate script.
=> Fix build commands

docs/configuration.md
The `config` folder was moved in https://github.com/lyft/amundsenfrontendlibrary/pull/95. There are links in our doc pointing to those files that needed to be updated.
=> Update links to application config files

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/SearchPage/styles.scss
This PR updates the style of the `.search-error` text to be more readable, using a color value that meets contrast guidelines for text.
**Before**
**After**
=> Change '.search-error' color to text-medium

amundsen_application/static/jest.config.js, amundsen_application/static/js/components/AnnouncementPage/index.tsx, amundsen_application/static/js/components/AnnouncementPage/tests/index.spec.tsx, amundsen_application/static/js/components/BrowsePage/index.tsx, amundsen_application/static/js/components/BrowsePage/tests/index.spec.tsx, amundsen_application/static/js/components/Footer/index.tsx, amundsen_application/static/js/components/Footer/tests/index.spec.tsx, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/tests/index.spec.tsx, amundsen_application/static/js/components/NotFoundPage/tests/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/tests/index.spec.tsx, amundsen_application/static/js/components/common/AvatarLabel/tests/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/tests/index.spec.tsx, amundsen_application/static/js/config/config-types.ts, amundsen_application/static/js/fixtures/globalState.ts
This PR adds unit test coverage for the following components: `AnnouncementPage`,`BrowsePage`, `Footer`, `NavBar`, `NotFoundPage` and `ProfilePage`.  
`Footer` will require more effort to cover in the future, I ran into problems mocking the `moment-timezone` library.
=> Increase Application Test Coverage

amundsen_application/static/js/components/Footer/index.tsx, amundsen_application/static/js/components/NavBar/index.tsx
The navbar and footer components were incorrectly referencing `state` for values that only existed in `props`.
=> Fix navbar and footer state bugs

amundsen_application/static/js/ducks/user/sagas.ts
The `/user` API is not implemented yet 
See: https://github.com/lyft/amundsenfrontendlibrary/pull/90
=> Remove unimplemented user API call

amundsen_application/static/js/components/AnnouncementPage/index.tsx, amundsen_application/static/js/components/AnnouncementPage/tests/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx
In #99 we removed the use of `getDerivedStateFromProps` for components that did not need to do any manipulation of the passed props. 
As part of that PR the components should have been updated to leverage the values from `props` for rendering instead of `state`, because their function is to just render based on the props that are passed in from Redux.
=> Update to fully controlled component

amundsen_application/static/js/components/Tags/TagInfo/styles.scss
The 'tag-name' has an extra 8px margin-right when the 'tag-count' is not present for compact TagInfo
Make sure you have checked **all** steps below.
- Example: "Updates the version of Flask to v1.0.2"
1. Subject is separated from body by a blank line
1. Subject is limited to 50 characters (not including Jira issue reference)
1. Subject does not end with a period
1. Subject uses the imperative mood ("add", not "adding")
1. Body wraps at 72 characters
1. Body explains "what" and "why", not "how"
- All the public functions and the classes in the PR contain docstrings that explain what it does
=> Fixed extra margin compact TagInfo componenets

amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/tests/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/tests/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/tests/index.spec.tsx, amundsen_application/static/package-lock.json, amundsen_application/static/package.json
Previously there were console errors getting thrown in our unit tests regarding import errors:
The way we were importing the 3rd party `Avatar` from the `react-avatar` library was causing this error. The fix was to switch `import Avatar from 'react-avatar'` to `import * as Avatar from 'react-avatar'`.
I have updated all test files that use the `Avatar` component, as well as updated these tests to use the new recommended patterns detailed [here](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/recommended_practices.md). 
_Note_: Because of the syntax changes, test files may be easier to review by forgoing the diff and viewing the entire file. 
No documentation is needed as no new APIs have been added. …
=> Fix console warnings thrown in unit tests

docs/configuration.md
Verbatim copy of a Slack answer given by @danwom (better give credit where it’s due 🙂)
Having a few specific examples to go from in config docs always give you a good start
=> Docs: Add logo config example

amundsen_application/static/js/components/SearchPage/tests/index.spec.tsx
Forgot to remove this param from a previous PR. This parameter isn't being used and don't want the pattern to get propagated if anyone does a copy-paste.
No tests need to be updated for this kind of fix.
N/A
=> Remove unnecessary param in SearchPage setup()

amundsen_application/static/js/ducks/user/api/v0.ts, amundsen_application/static/js/ducks/user/types.ts
In https://github.com/lyft/amundsenfrontendlibrary/pull/90 we changed the payload returned by the `/api/auth_user`. Before #90 the response data was the user object -- now it is an object with a `user` key. We missed updating how we parse the response data before sending the result to the application. 
We're working on improving our test coverage, and tests for this part of the application have yet to be scaffolded. We aim to resolve this in the upcoming sprints.
N/A. This section of the application code has no relevant documentation.
- All the public …
=> Fix error in handling the logged in user response

.travis.yml, Makefile
Add Travis publish step to push Docker image into Dockerhub
Tested out Makefile locally. Testing publish to Travis is not feasible (too much effort AFAIK)
NA
=> [DPTOOLS-2252] Publish Docker image via Travis CI

docker-amundsen.yml, public.Dockerfile
This PR solves the following issue with the current amundsen-frontend docker image, which occurs after starting the container and navigating to the Web Page on <docker-host-ip>:5000:
`
amundsenfrontend    | 2019-05-01T17:57:21+0000.082 [ERROR] app.log_exception:1761 (1:Thread-3) - Exception on /favicon.ico [GET]
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
amundsenfrontend    |     response = self.full_dispatch_request()
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
amundsenfrontend    |     rv = self.handle_user_exception(e)
amundsenfrontend    |   File …
=> Add NPM install to Dockerfile and Environment variables to docker-amundsen.yml

amundsen_application/static/js/components/SearchPage/index.tsx, amundsen_application/static/js/components/SearchPage/tests/index.spec.tsx, amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/js/fixtures/globalState.ts
Title, we needed some form of loading state so that delays between search requests wouldn't look awkward. There's a small hack here where we need to handle GetPopularTables actions from the Search reducer but this'll be addressed in a follow up with the decoupling of popular tables and search in the new home page
N/A
N/A
=> Added loading spinner for search requests

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/metadata_utils.py, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/types.ts, tests/unit/api/metadata/test_v0.py
Previously all of our metadata APIs sent a set of fields `cluster`, `database`, `schema`, and `table` to identify the table record in metadata service. Those parameters were replaced by a single 'key'.
Modified metadata API tests to include `key` rather than the other fields.
=> Use table 'key' in Metadata APIs

docs/installation-aws-ecs/aws-ecs-deployment.md, docs/installation-aws-ecs/docker-ecs-amundsen.yml, docs/installation-aws-ecs/ecs-params.yml, docs/installation-aws-ecs/userData.sh
This commit contains instructions to deploy a non-productions Amundsen on AWS ECS and sample configuration files based on existing docker containers.
Added documentation on the deployment of non-production Amundsen on AWS ECS using aws-cli. This method is great for quick proof of concepts.
=> Docs on deployment of non-production Amundsen on AWS ECS using aws-cli

amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/tests/index.spec.ts
This PR fixes a bug with the `error_text` from a preview data failure not getting passed back to the frontend. 
1. The source of the bug was that in our error response handling, we passed back `e.response.data` when we needed to pass back `e.response.data.previewData`. 
2. I also realized we were processing the `axios` success response in the api call, yet processing the error response in the saga. All the `axios` response handling should have been part of the api call.
Updated saga tests to account for the new logic. This bug also exposes the fact that we need to complete unit test coverage to our `tableMetadata` apis to ensure we are handling responses correctly -- I have an internal ticket filed to complete this when I have the bandwidth.
N/A
Make sure you have checked **all** steps …
=> Fix preview data error handling

amundsen_application/static/js/ducks/feedback/api/tests/index.spec.ts, amundsen_application/static/js/ducks/feedback/api/v0.ts
I cannot remember the context of why this was added, and I wonder if this was a copy paste mistake. There is no reason for this api to have a timeout, and it risks causing issues if someone's custom mail client takes longer than that to complete the request. 
Updated api test.
N/A
=> Remove timeout on feedback submission api call

amundsen_application/static/css/_typography-default.scss, amundsen_application/static/js/components/SearchPage/SearchBar/constants.ts, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx
1. Adds back in the `database` option to the advanced search syntax help text.
2. Renders the `database` value in `TableListItem`. This is a stop gap implementation until our new designs are complete -- the `TableListItem` in this PR intentionally does not fully match the new designs.
Update `TableListItem` tests.
N/A
=> Add db to tablelistitem + re-add database to syntax help text

README.md
https://docs.python.org/3.4/library/http.html says 3.4 isn’t supported any more.
https://github.com/lyft/amundsen/issues/30 gives background on that we are in fact not able to build with 3.4
=> Bump minimum supported Python to 3.5

amundsen_application/static/js/components/SearchPage/ResourceSelector/index.tsx, amundsen_application/static/js/components/SearchPage/ResourceSelector/styles.scss, amundsen_application/static/js/components/SearchPage/ResourceSelector/tests/index.spec.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/styles.scss, amundsen_application/static/js/components/SearchPage/SearchFilter/tests/index.spec.tsx, amundsen_application/static/js/components/SearchPage/SearchPanel/index.tsx, amundsen_application/static/js/components/SearchPage/SearchPanel/styles.scss, amundsen_application/static/js/components/SearchPage/SearchPanel/tests/index.spec.tsx, amundsen_application/static/js/components/SearchPage/index.tsx, amundsen_application/static/js/components/common/Inputs/CheckBoxItem/index.tsx, amundsen_application/static/js/components/common/Inputs/CheckBoxItem/styles.scss, amundsen_application/static/js/components/common/Inputs/CheckBoxItem/tests/index.spec.tsx
This PR created a `SearchFilter` component and subcomponents, and introduces some component modifications in preparation for introducing filtering. However the component will not yet be exposed -- _**the UI will remain the same when this is merged**_. Changes include:
1. Modified `SearchPanel` to be a stateless functional component, as it's purpose is to layout its children accordingly. It now takes any number of children and lays them out in a column.
1. Modified the use of `SearchPanel` on `SearchPage` according to the changes made to `SearchPanel`.
1. Created a re-useable `CheckBoxItem` that takes checkbox type input props and utilizes `props.children` for customizing what is rendered in the label.
2. Created a `SearchFilter` component. It currently takes `checkBoxFilterSections` -- an …
=> Initial implementation of SearchFilter

amundsen_application/api/mail/v0.py, amundsen_application/api/utils/notification_utils.py, amundsen_application/base/base_mail_client.py, amundsen_application/config.py, tests/unit/api/mail/test_v0.py, tests/unit/api/metadata/test_v0.py, tests/unit/utils/notification/test_v0.py
This PR cleans up some python code and adds unit test coverage for key notifications logic
Added tests to cover uncovered notifications logic.
Added/modified docstrings for relevant methods
=> Python cleanup + tests

amundsen_application/api/mail/v0.py, amundsen_application/api/utils/notification_utils.py, amundsen_application/base/base_mail_client.py, setup.py, tests/unit/api/mail/test_v0.py, tests/unit/utils/notification/test_v0.py
The current backwards incompatibility in the notifications project is simply due to the change in the name of a parameter on `base_mail_client.send_email`.  The parameter `optional_data`, in hindsight would be better called `options`. However because the change creates a backwards incompatibility -- i.e. this change will break everyone's current implementations of the `base_mail_client` -- I propose we keep the parameter as `optional_data` and update it in the future when we have more reason to create a new major release.
This PR reverts use of `options` back to `optional_data`, and the notifications project can become a new minor release at `1.1.0`.
Reverted use of `options` back to `optional_data`.
N/A
- In case …
=> Preserve compatibility in base_mail_client

amundsen_application/static/js/components/Tags/TagInfo/index.tsx, amundsen_application/static/js/components/Tags/TagInfo/tests/index.spec.tsx
- TagInfo now fires 'submitSearch' instead of using navigation
- Added tests for TagInfo
=> Fixed TagInfo to use Redux action

docs/application_config.md, docs/configuration.md, docs/flask_config.md
Relative URLs to docs in the same folder should do. They work for any branch, local copies of the docs - and should work better if we ever (or whenever :-) we get to having e.g a Sphinx generated site.
Manual GH markdown diff inspection
=> Relative URLs to child configuration docs

amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/tests/index.spec.ts, amundsen_application/static/js/ducks/search/utils.ts, amundsen_application/static/js/interfaces/Resources.ts
Added functionality to auto-select a resource on search. This picks the first resource type with results (table -> user -> dashboard). If there are no results, a default (table) is selected.
Added tests for the auto-select utility function.
=> Added auto-select resource after searching

amundsen_application/api/mail/v0.py, amundsen_application/api/metadata/v0.py, amundsen_application/static/js/components/TableDetail/OwnerEditor/index.tsx, amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, amundsen_application/static/js/ducks/tableMetadata/api/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/owners/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/owners/tests/index.spec.ts, setup.py, tests/unit/api/mail/test_v0.py, tests/unit/api/metadata/test_v0.py
This PR improves the behavior of the automatic notifications that occur when an owner is added or removed. We now send a notification only on success of adding/removing the owner, and only if the user is not an alumni and is not a team.
The following changes were made to achieve this:
1. Notifications for owner notifications was removed from the Flask layer, all notifications are now triggered by some logic that occurs in the Redux layer. This provides us with more flexibility to explicitly call the `/notification` endpoint in specific cases.
2. Modified the method that generates the request to update the owner. If the update request succeeds, a request is added to the chain to get the user data for the given owner. A helper method evaluates if the user meets the criteria to get a …
=> Improve behavior of notification sending for owner editing

amundsen_application/static/css/_popovers.scss, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/index.tsx, amundsen_application/static/js/components/TableDetail/DetailList/DetailListItem/styles.scss
This PR truncated the column type for strings that start with `array`, `struct`, or `map` which have extended information. e.g. if the type is `array`, the text `array` will be rendered. If the type is `array...`, the text will be rendered as `array<...>` and on click will show the full text.
Implementation wise I considered creating a set of configurable "formatters" as we have these new use case to change how the column type is rendered (different folks might want different things) as well as numerical values (different folks will need different things due to internationalization). However given that a new design will be worked on for the concept of nested column types and this fix is a just a patch, I held off on introducing any new configurations until we understand the final …
=> Truncate the column type

amundsen_application/static/js/components/common/EditableText/styles.scss
Removed the 'inline-block' rule for markdown generated 'p' tags. This was causing multiple lines to render together.
=> Fixed linebreaks with Markdown descriptions

amundsen_application/wsgi.py, local.Dockerfile, public.Dockerfile, setup.py
Optimize docker - see https://github.com/lyft/amundsen/issues/109
You may wonder why the renaming in `amundsen_application/wsgi.py` from `app` to `application` is done. It turned out for `Gunicorn` to run it was needed otherwise it spat this out in the log:
```
amundsenfrontend    | 2019-09-26T18:48:23+0000.384 [INFO] __init__.create_app:47 (8:MainThread) - Using metadata service at http://amundsenmetadata:5000                                             
amundsenfrontend    | 2019-09-26T18:48:23+0000.384 [INFO] __init__.create_app:48 (8:MainThread) - Using search service at http://amundsensearch:5000                                                 
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File …
```
=> optimize docker

amundsen_application/__init__.py, amundsen_application/api/utils/notification_utils.py, amundsen_application/config.py, amundsen_application/log/action_log.py, amundsen_application/static/js/interfaces/Notifications.ts, docs/flask_config.md, tests/unit/utils/notification/test_utils.py
This PR adds a new feature to allow the configuration of custom and completes some cleanup in the notifications code.
1. There is a new config variable `INIT_CUSTOM_ROUTES`. It is a `Callable` that takes a Flask application and is called during `create_app`. This allows individuals to configure custom endpoints to support custom logic. In our case at Lyft, we are using it to hook on a new endpoint to our frontend application that will process some internal callback to generate some custom metrics.
2. In our python code I have added an enum class `NotificationType`, that matches the `NotificationType` interface in the frontend application, and replaced all usages of hardcoded notification type strings to leverage the enum class. This makes it easier to maintain the code snd prevent some …
=> Custom routes + Further notification cleanup

amundsen_application/api/utils/notification_utils.py, amundsen_application/static/js/components/TableDetail/index.tsx, tests/unit/utils/notification/test_utils.py
This PR adds the `source` logging parameter to notification email links and sets the source to "notification"
Updated notification_utils test. Noted that we should eventually set up some improved helper methods to not have to manually update the expected html string any time there is a change.
N/A
=> Add source for notification email links

amundsen_application/static/js/ducks/tableMetadata/api/v0.ts
Fix a duplicate `/v0` in the API for `getTableDescription`
=> Fixed broken get_table_description API

amundsen_application/static/js/components/TableDetail/OwnerEditor/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/index.tsx
Making table Owner items clickable like table Frequent Users.
An item click leads to a redirect to a user's homepage.
No new tests.
No new documentation.
closes lyft/amundsen#146
=> Make table owner items clickable

amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/ResultItem/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/ResultItem/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/SearchItem/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/SearchItem/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/index.tsx, amundsen_application/static/js/ducks/rootSaga.ts, amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/types.ts
The current inline search saga behavior uses `debounce`, which prevents a request from being fired for each keystroke. However it does not fully prevent against a slower-typing user seeing intermediate results as they type. **_Example:_** Depending on how fast someone types "ttannis", they could briefly see no results for "ttan" as they are still typing. 
With the existing changes, this "glitchy" behavior is much less likely to happen, as the UI will only show the results of the latest debounced request. Alternatively we *could* have increased the debounce time, but this would also have led to a slower experience for users who type quickly. I find the current changes to be a good middle-ground and improvement upon the existing experience.
Added `logClick` on the clickable components in …
=> Inline Search Improvements + Logging

amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/SearchItem/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/SearchItem/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/constants.ts, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/styles.scss, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/tests/index.spec.tsx, amundsen_application/static/js/fixtures/search/inlineResults.ts
This PR covers changes from our Design QA on the inline results feature. Changes include:
1. When the search is occurring `InlineSearchResults` no longer shows the large `LoadingSpinner` in place of the results. Instead `SearchItem` will show a small `LoadingSpinner` instead.
2. When there are no results for a particular resource, the `ResultItemList` for that resource will not be rendered. Instead `SearchItem` will show "No results found" for that resource. 
3. Minor css changes regarding the spacing of the items in `InlineSearchResults`.
1. The above items required connecting `SearchItem` to the application state so that it can get the inlineResults state.
2. `mapStateToProps` tests for `SearchItem` takes a new approach that I intend to carry forward. It is based on importing test …
=> Improve InlineSearch UI

amundsen_application/static/js/components/Feedback/FeedbackForm/BugReportFeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/BugReportFeedbackForm/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RatingFeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RatingFeedbackForm/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RequestFeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RequestFeedbackForm/tests/index.spec.tsx, amundsen_application/static/js/components/Feedback/index.tsx, amundsen_application/static/js/components/Feedback/styles.scss, amundsen_application/static/js/components/Feedback/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/styles.scss
This PR covers a cleanup task to unify the look and feel of our "pop-up" forms, `RequestMetadataForm` and `FeedbackForm`. Design requested:
1. Match title style of the request form
2. Match button style of the request form, and left align with form instead of right
3. Make sure the cancel/close icon matches in style and position
Tests updated as needed based on component changes.
N/A. Just UI improvements.
=> Consolidate look&feel of request/feedback forms

Makefile, amundsen_application/config.py, amundsen_application/oidc_config.py, public.Dockerfile, requirements3-oidc.txt, setup.py
I was making my own image with oidc based on the instructions in the repo and I was thinking it would be simpler if the main build processes just also made that image. 
I ran both images this builds and everything seems to work. 
If everyone is happy with this approach, I can do the same for the metadata repo and update the helm chart too.
=> Adding a separate oidc version of the image

amundsen_application/api/metadata/v0.py, tests/unit/api/metadata/test_v0.py
This PR properly handles failed `get_bookmarks` requests
I added a test to check this failure state
=> Handle get bookmark failure properly

amundsen_application/static/css/_layouts.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/css/styles.scss, amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss, amundsen_application/static/js/components/NavBar/tests/index.spec.tsx, amundsen_application/static/js/components/ProfilePage/constants.ts, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/styles.scss, amundsen_application/static/js/components/ProfilePage/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/Breadcrumb/index.tsx, amundsen_application/static/js/components/common/Breadcrumb/styles.scss, amundsen_application/static/js/components/common/Breadcrumb/tests/index.spec.tsx, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/tests/index.spec.ts, amundsen_application/static/js/index.tsx
Update the profile page design have a similar layout as the table details page.
=> Update profile page design

setup.cfg
This should fix the master build. We raised the coverage threshold in a previous PR, but it's not giving enough buffer -- we expect coverage to naturally go up/down within a couple percentage points during regular development even when folks are still covering important logic.
N/A
N/A
=> Lower python coverage

amundsen_application/static/css/_inputs.scss, amundsen_application/static/js/components/Feedback/FeedbackForm/BugReportFeedbackForm/index.tsx, amundsen_application/static/js/components/Feedback/FeedbackForm/RequestFeedbackForm/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/InputFilter/index.tsx, amundsen_application/static/js/components/TableDetail/RequestMetadataForm/index.tsx
=> Disabled autocomplete for text and email input fields

amundsen_application/static/js/components/NavBar/index.tsx, amundsen_application/static/js/components/SearchPage/index.tsx, amundsen_application/static/js/components/SearchPage/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/index.tsx, amundsen_application/static/js/ducks/search/filters/reducer.ts, amundsen_application/static/js/ducks/search/reducer.ts, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/types.ts
This PR further addresses issues from our user interviews, namely:
1. Persisting filters when re-executing a search on the `SearchPage`
2. Removing the requirement of a search term, which allows users to execute higher level searches across categories, e.g. "I'm looking for all resources in this schema"
**NavBar**
1. Passes the current location to `SearchBar`
**SearchBar**
1. Removed `isFormValid` check and requirement for a search term to execute a search
2. Passes a boolean to the `submitSearch` action to specify whether or not the existing filters should be used in this search.
**SearchPage**
1. Utilizes a new `hasFilters` boolean to assist with the error message logic. Our new user flow allows for users to clear all search input (search term + filters), in which case they now see a …
=> Improve user search experience

amundsen_application/static/js/components/SearchPage/SearchFilter/FilterSection/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/styles.scss, amundsen_application/static/js/config/config-default.ts, amundsen_application/static/js/config/config-types.ts
We want to offer some optional help text for each filter section. This has been added to the optional `filterCategories` configuration, and if present will result in an `InfoButton` in the filter section header -- exact text will likely still go through some iteration in design qa
TODO: As part of final feature branch review
TODO: As part of final feature branch review
=> Add support for configurable filter section help text

docs/application_config.md, docs/flask_config.md
Updates documentation for how to enable issue tracking, what it does, and how to configure it. 
N/A
Updated documentation for issue tracking 
=> Add documenation for JIRA feature

amundsen_application/static/js/components/common/Inputs/CheckBoxItem/index.tsx, amundsen_application/static/js/components/common/Inputs/CheckBoxItem/tests/index.spec.tsx, amundsen_application/static/js/ducks/search/sagas.ts, amundsen_application/static/js/ducks/search/tests/index.spec.ts
This PR fixes the following issues:
1. Use `pageIndex = 0`  when executing a search from an updated filter. This is because filtering makes the context of the previous pageIndex obsolete, because the number of results are expected to change.
2. `CheckBoxItem` did not update itself if `checked` was `undefined`. This currently possible because of the way that we create the items [here](https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/components/SearchPage/SearchFilter/CheckBoxFilter/index.tsx#L41) with `checked={ this.props.checkedValues[value] }`. This fix opts to fix the issue in `CheckBoxItem` to decrease the chance of the bug occurring again in any future usages. 
Updated tests according to modifications made to the code.
N/A for this kind of …
=> Filter Fixes

amundsen_application/static/js/components/TableDetail/TableHeaderBullets/index.tsx, amundsen_application/static/js/components/TableDetail/TableHeaderBullets/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/SearchItemList/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/tests/index.spec.tsx
This PR creates a separate `TableHeaderBullets` component. No functionality has changed, the component was separated so that it can be more easily overridden. 
1. Added test for component
2. Also found the solution for getting TypeScript to not complain about mock implementations of imported methods.
N/A. No behavior is being modified and no new features are added.
=> Create TableHeaderBullets component

amundsen_application/api/search/v0.py, amundsen_application/api/utils/search_utils.py, tests/unit/api/search/test_v0.py, tests/unit/utils/test_search_utils.py
This PR updates the Flask endpoint that calls the search service, such that if there are filters it will `POST` to the [SearchTableFilter API](https://github.com/lyft/amundsensearchlibrary/blob/master/search_service/api/table.py#L121) else maintain a `GET` to the [SearchTableAPI](https://github.com/lyft/amundsensearchlibrary/blob/master/search_service/api/table.py#L34)
Updates tests according to changes.
N/A. 
=> Update search_table endpoint

amundsen_application/config.py, amundsen_application/proxy/issue_tracker_clients/jira_client.py, tests/unit/issue_tracker_clients/test_jira_client.py
Passing `reporter={'name': valid_jira_id}` sets the reporter for the issue. This current workaround can and should probably be improved in the future. It will not work for users who have aliases or any case where the `jira_id` is not the employee's email handle. 
Updated relevant test.
N/A for now. If we keep this implementation we should call out the limitation above in the feature documentation.
=> Add reporter for JIRA Issue Creation

amundsen_application/api/search/v0.py, amundsen_application/api/utils/search_utils.py, tests/unit/api/search/test_v0.py, tests/unit/utils/test_search_utils.py
This PR updates our search logic to transform the frontend filter shape --> search service filter shape before calling `_search_table`, so that our logs will capture the exactly what gets passed to the search service. Motivations for doing this are:
1. The data shape from the frontend application state is not documented anywhere and should be treated as a black box. It is more subject to change based on application needs and new features.
2. The data shape for filters on the search service api  is more concise
Updated tests according to changes.
N/A for this kind of change. …
=> Update logic to transform filters then call _search_table

amundsen_application/api/search/v0.py, amundsen_application/api/utils/search_utils.py, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx, amundsen_application/static/js/interfaces/Resources.ts, tests/unit/api/search/test_v0.py
Some tables have badges which are displayed on the table detail view page. These badges contain useful information that can help users determine which table they want to look at. This change surfaces that information on search. 
Modified tests to confirm that the results are displayed
N/A
=> Update search results to include badges and display them

amundsen_application/static/js/components/SearchPage/SearchFilter/InputFilter/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/InputFilter/tests/index.spec.tsx
Because search is currently case sensitive, the filter will not return results if someone enters uppercase. To address this `InputFilter` will do the same thing `SearchBar` has been doing, and cast the value to lower case automatically on input.
As a note, the ideal experience for this would be addressed by: https://github.com/lyft/amundsen/issues/283
Updated applicable test
N/A
=> Cast input to lowercase like we do for SearchBar

amundsen_application/config.py, amundsen_application/static/js/components/TableDetail/EditableSection/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/constants.ts, amundsen_application/static/js/components/TableDetail/index.tsx, tests/unit/utils/test_metadata_utils.py
Some cleanup on top of https://github.com/lyft/amundsenfrontendlibrary/pull/381
1. Python unit tests were updated to explicitly test the behavior of helper functions added in `metadata_utils`
2. Placed hardcoded text from `TableDetail` into a `constants` file. We are separating out hardcoded user-readable text for out components because it will make them easier to update in the future -- especially if we eventually allow for constants for be overwritten.
3. Updated the test for the `EditableSection` title to verify that convertText() is called and the result of that method is what gets rendered. 
Included above.
N/A. Features have not been modified.
- In case you are adding a dependency, check if the license …
=> Clean up some tests for programmatic descriptions feature

amundsen_application/static/js/components/TableDetail/TableIssues/index.tsx, amundsen_application/static/js/components/TableDetail/TableIssues/styles.scss
Very long JIRA titles are overflowing on to the next line. This shrinks the width at which overflow is used for the list of issues so that doesn't happen. 
N/A
N/A
=> Fix overflow for issue tracking feature

amundsen_application/static/js/components/TableDetail/LineageLink/index.tsx
For tables with no lineage url or empty string we used to not show the compiler works link. There was an oversight on the new design logic to account for this. The effect is that lineage links are rendered and Chrome makes it link back to the same page when `href` is undefined.
This are remains untested.
N/A
=> Do not render component if no lineage url

amundsen_application/static/js/components/common/SearchBar/constants.ts, amundsen_application/static/js/components/common/SearchBar/index.tsx, amundsen_application/static/js/components/common/SearchBar/tests/index.spec.tsx
1. Some users still entered advanced search syntax into the search bar.
2. If a colon is in the search term, it will break the filter endpoint.
3. A fix was made in amundsensearchlibrary to return HTTPStatus.BAD_REQUEST in this case
This PR aimed to create a better experience for this on the frontend, by surfacing information about non-successful requests. 
The initial plan to was show different messages on the `SearchPage` for 5xx and 4xx errors. However the work effort turned out to be too great given current priorities. Our search bar searches batches the 3 requests to each resource endpoint and we would have to restructure this to be able to capture error codes only for the resources that fail  and store it on the search state for that resource.
Because of the scope creep my current …
=> Prevent entering of ':' into search term

amundsen_application/api/preview/dashboard/v0.py, amundsen_application/static/js/components/DashboardPage/ImagePreview/constants.ts, amundsen_application/static/js/components/DashboardPage/ImagePreview/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/ImagePreview/index.tsx, amundsen_application/static/js/components/DashboardPage/ImagePreview/styles.scss, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/DashboardPage/styles.scss, amundsen_application/static/js/components/DashboardPage/test.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/ResultItem/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/ResultItem/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/tests/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/tests/index.spec.tsx, amundsen_application/static/js/ducks/dashboard/api/v0.spec.ts, amundsen_application/static/js/ducks/dashboard/api/v0.ts, amundsen_application/static/js/ducks/dashboard/reducer.ts, amundsen_application/static/js/ducks/dashboard/sagas.ts, amundsen_application/static/js/ducks/dashboard/tests/reducer.spec.ts, amundsen_application/static/js/ducks/dashboard/tests/sagas.spec.ts, amundsen_application/static/js/ducks/dashboard/types.ts, amundsen_application/static/js/ducks/rootSaga.ts, amundsen_application/static/js/fixtures/dashboard/preview.ts, amundsen_application/static/js/fixtures/globalState.ts
This PR adds the UI support for dashboard previews. There is also some code cleanup from https://github.com/lyft/amundsenfrontendlibrary/pull/424
1. Created an `ImagePreview` component and added it to `DashboardPage`. This component supports showing the url if it exists, and supports showing error messages from the API if the request fails.
2. Added support in `ducks` to request the dashboard image preview. This is a special case where we already know what the url for each resource us going to be -- so the success response just returns that url, and the failure case has to do some extra parsing of the response to additionally return the error code and error message for the UI.
1. Updated the links to `DashboardPage` to put the `uri` in the search params
2. Resolved issue of `title` vs …
=> Add Dashboard Preview UI Support

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/search_utils.py, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/DashboardPage/test.tsx, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/tests/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/common/Bookmark/BookmarkIcon/index.tsx, amundsen_application/static/js/components/common/Bookmark/BookmarkIcon/tests/index.spec.tsx, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/index.tsx, amundsen_application/static/js/components/common/Bookmark/MyBookmarks/tests/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx, amundsen_application/static/js/ducks/bookmark/api/tests/index.spec.ts, amundsen_application/static/js/ducks/bookmark/api/v0.ts, amundsen_application/static/js/ducks/bookmark/reducer.ts, amundsen_application/static/js/ducks/bookmark/tests/index.spec.ts, amundsen_application/static/js/ducks/bookmark/types.ts, amundsen_application/static/js/ducks/user/api/tests/index.spec.ts, amundsen_application/static/js/ducks/user/reducer.ts, amundsen_application/static/js/ducks/user/tests/index.spec.ts, amundsen_application/static/js/ducks/user/types.ts, amundsen_application/static/js/fixtures/globalState.ts, amundsen_application/static/js/interfaces/Resources.ts, tests/unit/api/metadata/test_v0.py, tests/unit/api/search/test_v0.py, tests/unit/utils/test_search_utils.py
This PR supports the following features:
1. Support the ability to bookmark a dashboard via appropriate changes to `BookmarkIcon` and bookmark api calls. Note the `resourceType` passed is no longer a string but now and actual `ResourceType` type.
2. Support the ability to show bookmarks and owned on the `ProfilePage`. The application state now stores `bookmarks` and `own` values as a `ResourceDict<Bookmark[]>` or `ResourceDict<Resource[]>` and the desired information is easily accessed through out the application by `ResourceType`.
Tests added to cover changes.
N/A …
=> Dashboard Bookmarks & Dashboard ProfilePage support

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/NavBar/styles.scss
Adjusts the line height on some elements of the navigation bar.
After:
Before:
No tests, this is an esthetic change
Nothing New
- [] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
=> Aligns text elements on the navigation bar

amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/ResultItem/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/ResultItem/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/styles.scss
Fixes icons on the typeahead suggested results not showing
Updates test and moves it out of the /test folder
Updated tests
- [] In case of new functionality, my PR adds documentation that describes how to use it.
=> Fixes typeahead result icons not showing

amundsen_application/static/js/components/DashboardPage/ImagePreview/index.tsx
When a dashboard detail page in Amundsen loads, it attempts to load an image preview of the dashboard from Mode, if it fails it gives a Mode link, with this change Mode link will open in new tab so that user will not loose context.
No new tests were added or modified.
No change
=> [AMD-1419] Added target property to image preview

amundsen_application/static/js/components/SearchPage/styles.scss
At some point, our styles for the height of the `SearchPage` stopped working as intended. The page was no longer taking up the full height unless there was content to fill it -- this could be observed on an empty `SearchPage` where `Dashboard` or `People` is selected as the resource.
I was unable to trace when this actually broke, but updated the css accordingly to fix the issue.
_Before_
_After_
N/A for this kind of fix
N/A for this kind of fix
=> fix: Fix SearchPage min-height

amundsen_application/base/examples/example_announcement_client.py, docs/configuration.md, docs/examples/announcement_client.md
Until now there was no example on how to prepare announcement_client for `Announcements` feature.
I've added (and documented) exemplary client using SQL Alchemy so users can quickly adapt it to their own needs and start using it. It also uploads mock announcements data to get a feel what can be expected from the feature.
Added docs for `announcement_client` and extended configuration documentation.
- All the public python functions and the …
=> Document and provide example for announcement_client

amundsen_application/static/js/components/common/Flag/index.tsx, amundsen_application/static/js/components/common/Flag/tests/index.spec.tsx
Currently, if you pass a null value as the `text` property to a `Flag` component with any sort of capitalization rule (e.g., `CaseType.SENTENCE_CASE`), the attempt to call string methods on the null value results in errors that completely block page load. This change quietly coerces null values to empty strings in `convertText()` to avoid this issue.
I ran into this issue while trying to load a dashboard with a null value for `last_run_status`.
Added unit test to `components/common/Flag/tests/index.spec.tsx`
n/a
- [n/a] In case of new functionality, my …
=> fix: null string passed as text to Flag component prevents page load

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/DashboardPage/ImagePreview/index.tsx, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/EditableSection/constants.ts, amundsen_application/static/js/components/common/EditableSection/index.spec.tsx, amundsen_application/static/js/components/common/EditableSection/index.tsx
This PR make a series of UI and style fixes described below.  Each commit is scoped to a particular task for easier review.
This fix is also included in https://github.com/lyft/amundsenfrontendlibrary/pull/467, but will just resolve on merge vs. reverting the commit.
**Before:**
**After:**
Design proposed to make the metadata sections in the left panel have a min-height, which will currently be 70px. The reason for this is so that most pages becomes more aesthetically pleasing by having column items align vs. before where many cases would be just slightly off. The design sentiment is that either items will align or be very clearly not aligned. 
**Before:** (items slightly off)
**After:**
A readOnly `EditableSection` was rendering the edit button and the empty popover when not given the …
=> fix: Miscellaneous UI Fixes

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/DashboardPage/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/TableDetail/OwnerEditor/styles.scss, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.spec.tsx, amundsen_application/static/js/components/common/ResourceListItem/DashboardListItem/index.tsx, amundsen_application/static/js/components/constants.ts
It is possible for dashboard resources to be missing a `last_run_timestamp` and a `last_successful_run_timestamp`. This PR updates the areas where we display dashboard timestamps to show some default text for this case, to reduce confusion for the user.
**End Result:**
This PR also make a style fix to ensure the the text color for the `AvatarLabel` components in the left panel is `$text-primary`. 
Updates tests to verify changes introduced.
N/A
=> fix: Fix dashboard timestamp & dashboard owner text color

tests/unit/api/metadata/test_v0.py, tests/unit/api/search/test_v0.py
This PR updates some of the weaker assertions we are using in our python tests, where tests fail if there are changes in `amundsen-common` that add new parameters. This change should prevent tests from failing when the `User` model is in development.
There is more work to be done here in terms of making our tests verify specific values and applying these changes across all tests, however this PR aims to just unblock Travis failures on this repo right now. 
See above.
N/A
- All the public python functions and the classes in the PR contain docstrings that …
=> fix: Update some python assertions

amundsen_application/api/preview/dashboard/v0.py, amundsen_application/config.py, amundsen_application/dashboard_preview/mode_preview.py, requirements.txt, setup.py, tests/unit/dashboard_preview/test_mode_preview.py
Added `access control` on Mode dashboard preview.
- Calls `metadata service` is verify if user is `is_active` and has `mode_user_id`. Because, all Mode dashboard is in shared space, this two conditions are enough to validate the access.
- If user is not registered in `Mode` (does not have permission to view the report), it returns `401` Unauthorized.
Unit tests updated.
Integration test done.
docstring
=> feat: Mode dashboard preview ACL

amundsen_application/static/css/_buttons-default.scss, amundsen_application/static/js/components/SearchPage/SearchFilter/FilterSection/index.spec.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/FilterSection/index.tsx, amundsen_application/static/js/components/SearchPage/SearchFilter/styles.scss
Adds a style for .btn-link
Uses that style on the filters section
Removes nesting on the filters section styling
Updated tests
=> feat: Uses button for "clear" on filters

amundsen_application/static/css/_icons.scss, amundsen_application/static/js/components/ProfilePage/index.tsx
Recent style changes caused a UI regression where the hover state over the user icon on the ProfilePage was not correct, showing an indigo background.
**Before**
To fix this issue I reverted to using the previous mask image styling for this use case.
**After**
N/A
N/A
=> fix: Update user icon on ProfilePage

amundsen_application/api/metadata/v0.py, amundsen_application/static/js/components/TableDetail/TableDashboardResourceList/index.spec.tsx, amundsen_application/static/js/components/TableDetail/TableDashboardResourceList/index.tsx, amundsen_application/static/js/components/TableDetail/index.spec.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/ResourceList/styles.scss, amundsen_application/static/js/ducks/tableMetadata/api/helpers.spec.ts, amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/types.ts, amundsen_application/static/js/fixtures/globalState.ts, amundsen_application/static/js/fixtures/metadata/table.ts, amundsen_application/static/js/interfaces/TableMetadata.ts, tests/unit/api/metadata/test_v0.py
This PR fixes the issue of the `TableDetail` page being unable to render when the metadata endpoint for related dashboards is not properly implemented or otherwise has an issue and returns a non-200 code. The cause of the issue was coupling the request for table metadata with the request for related dashboards -- if the related dashboard request failed then the entire page failed to load. 
This PR separate the logic of the related dashboards feature into a separate component and decouples some API calls. Support also includes showing error text from the response when there is an issue with the related dashboard request. 
Further details implementation details have been included inline.
Tests updated to reflect changes.
N/A
Make sure you have checked **all** steps below to ensure a timely …
=> fix: Separate related dashboards component & request

.travis.yml
The fix from https://github.com/lyft/amundsenfrontendlibrary/pull/498 was applied to the `node_js` section of the instead of the `python` section, which is what is error-ing when trying to create the release. This PR updates that.
N/A
N/A
=> fix: Update travis.yml

amundsen_application/api/search/v0.py, tests/unit/api/search/test_v0.py
With the changes introduces in this PR: https://github.com/lyft/amundsensearchlibrary/pull/111 , if your user index feature is not implemented in the search i.e., has `pass`, then the frontend does not work and crashes. This PR will fix this issue. 
Added the corresponding test case!
N/A
=> fix: Make sure not to crash user search api when search service returns empty dict

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/DashboardPage/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/index.tsx, tests/unit/api/metadata/test_v0.py
This PR supports markdown in dashboard descriptions. 
1. Use `ReactMarkdown` to display dashboard descriptions
2. Update styles to ensure font size is `16px`, and removing the extra margins from the `<p>` (paragraph) element used in `ReactMarkdown`. This is needed to keep things inline with design specifications.
1. Updates `DashboardPage` tests to reflect changes.
N/A, but will be called out in the next release.
=> feat: Support markdown for dashboard descriptions

amundsen_application/static/js/components/DashboardPage/QueryList/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/QueryList/index.tsx, amundsen_application/static/js/components/DashboardPage/QueryListItem/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/QueryListItem/index.tsx, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/NavBar/styles.scss
This PR addressed https://github.com/lyft/amundsen/issues/546 by passing the product name to the `QueryListItem` from its parents, in order to show the appropriate product display name in the UI. The `product` property is passed from `DashboardPage` -> `QueryList` -> `QueryListItem`.
N/A
N/A
=> fix:  Pass product name to query list item UI

amundsen_application/static/js/components/TableDetail/ColumnList/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx
We have provided feature for making table and column description un-editable, in this PR we are providing link to source file from column's edit button if someone wants to change column description at source file.
Edit link and source is same as table source link. 
NA
NA
=> fix: Getting tooltip on edit button of Column Description if un-editable

amundsen_application/static/js/components/DashboardPage/index.tsx
Right now, dashboard descriptions aren't styled the same way as table descriptions, since dashboard descriptions are not in `.editable-text`. The main consequence of this is that headings in dashboard descriptions can be very large.
None
None
=> fix: Wrap dashboard description in .editable-text to enforce description styles

amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/config/config-utils.ts
We were missing support to apply the columns description length configuration to the `ColumnDescEditableText`.
N/A
N/A
=> fix: Apply column description length configuration

amundsen_application/static/css/_layouts.scss, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/common/EditableText/styles.scss
This PR is an extension of https://github.com/lyft/amundsenfrontendlibrary/pull/520, updating the fix to use the approach of taking `markdown-wrapper` styles that were only applied to `EditableText`, and instead applies them to all `markdown-wrapper` components used within the resource detail left panel layout.
See https://github.com/lyft/amundsenfrontendlibrary/pull/520#issuecomment-665305296 for further context.
N/A. CSS changes only.
N/A. CSS changes only.
- All the public python functions and the classes in the PR contain docstrings that explain what …
=> fix: Update markdown wrapper styles

amundsen_application/api/utils/metadata_utils.py
The for loop where the column editable state got set was done written incorrectly. It was nested inside a check for `app.config['COLUMN_STAT_ORDER']`, so it would not be set if the configuration did not exist. This PR updates the logic to work as intended. 
N/A
Will be called out in release. 
=> fix: Correctly set column editable state

amundsen_application/static/js/components/Footer/index.tsx, amundsen_application/static/js/ducks/tableMetadata/reducer.ts
Footer shows when did Amundsen last indexed, it loads properly for first time but when we navigate to other pages it goes into loading state forever.
No addition
No addition
=> fix: Footer consistently in loading state

amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts
For now we are passing the User Display Name to apply certain operations on the data owner. 
Since we are using the same model as the User for the Data Owner, it should be the user_id for those operations. 
NA
NA
=> fix: Make user_id the id to use for the Owner operations

amundsen_application/static/js/components/DashboardPage/index.spec.tsx, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/components/common/Flag/index.spec.tsx, amundsen_application/static/js/components/common/Flag/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/UserListItem/index.spec.tsx
This PR fixes two issues:
1. `Flag` usage on `DashboardPage` should have referenced existing `BadgeStyle` enums vs. hardcoding duplicate text.
2. Leverage `escapeHtml={false}` on `ReactMarkdown` for our description component. This attribute needs to be set to allow rendering of useful html such as `<img>` tags
3. Other changes come from running lint-fix.
N/A, no functionality has been changed
N/A, no functionality has been changed
=> fix: DashboardPage Flag usage; Markdown to render HTML

amundsen_application/static/webpack.common.ts, amundsen_application/static/webpack.dev.ts, amundsen_application/static/webpack.prod.ts
In production, it's helpful to use content addressing to guarantee cache busting
when publishing changes.
However, in development, because the server serves a static copy of the
index.html, that means that changing the Javascript bundle or CSS requires an
otherwise-unnecessary restart of the server.
This change makes the CSS and JS assets use fixed filenames so that a server
restart isn't needed.
Downside of this approach is there's now a dev/prod disparity and the config is
more spread out between files. The positive is we don't need to modify the
semantics of the server at all.
AFAICT, there are no selenium-style integration tests, so I'm not aware of an established pattern to test this behavior. Happy to add tests if there's a pathway, though!
The docs don't mention this stuff right …
=> build: use static CSS and JS filenames in dev

amundsen_application/static/js/components/DashboardPage/QueryListItem/CodeBlock.tsx, amundsen_application/static/js/components/Feedback/index.tsx, amundsen_application/static/js/components/NotFoundPage/index.tsx, amundsen_application/static/js/components/SearchPage/SearchPanel/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnList/index.tsx, amundsen_application/static/js/components/TableDetail/FrequentUsers/index.tsx, amundsen_application/static/js/components/TableDetail/LineageLink/index.tsx, amundsen_application/static/js/components/TableDetail/ResourceReportsDropdown/index.tsx, amundsen_application/static/js/components/TableDetail/SourceLink/index.tsx, amundsen_application/static/js/components/TableDetail/TableHeaderBullets/index.tsx, amundsen_application/static/js/components/TableDetail/WriterLink/index.tsx, amundsen_application/static/js/components/common/AvatarLabel/index.tsx, amundsen_application/static/js/components/common/BadgeList/index.tsx, amundsen_application/static/js/components/common/Breadcrumb/index.tsx, amundsen_application/static/js/components/common/EntityCard/index.tsx, amundsen_application/static/js/components/common/Flag/index.tsx, amundsen_application/static/js/components/common/FlashMessage/index.tsx, amundsen_application/static/js/components/common/InfoButton/index.tsx, amundsen_application/static/js/components/common/Inputs/CheckBoxItem/index.tsx, amundsen_application/static/js/components/common/ResourceListItem/SchemaInfo/index.tsx, amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/ResultItemList/ResultItem/index.tsx, amundsen_application/static/js/components/common/ShimmeringResourceLoader/index.tsx, amundsen_application/static/js/components/common/ShimmeringTagListLoader/index.tsx, amundsen_application/static/js/components/common/TabsComponent/index.tsx
Swaps React.SFC (Stateless Functional Component) for React.FC (Functional Component) types
React.SFC is now deprecated as mentioned [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364). This is a simple cleanup of all mentions to React.SFC in our repo.
Ran tests
=> chore: Deprecates React.SFC

amundsen_application/static/js/components/TableDetail/ColumnListItem/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx
For un-editable column descriptions that have no value and have no edit url, our current UI shows the `Description` header when the column is expanded. However there is nothing to show here and nothing the user will ever be able to interact with (e.g. no click to edit in url and no `Add Description`). As a result, we shouldn't show the header.
Will be adding tests
NA
=> fix: Uneditable descriptions with no value or possible actions should not show header

amundsen_application/static/js/components/TableDetail/OwnerEditor/constants.ts, amundsen_application/static/js/components/TableDetail/OwnerEditor/index.spec.tsx, amundsen_application/static/js/components/TableDetail/OwnerEditor/index.tsx, amundsen_application/static/js/components/common/EditableSection/index.tsx
1. Update `EditableSection` to correctly pass its `readOnly` state to `OwnerEditor`.  
2. Removed `readOnly` from the `OwnerEditor` component state. It is an artifact from old behavior.
3. Update rendering logic -- when there are no owners on a readOnly `OwnerEditor` we show the updated empty state from our designs.
Added unit tests for updated render logic.
N/A
=> fix: OwnerEditor readOnly support

amundsen_application/static/js/components/common/EditableSection/index.spec.tsx, amundsen_application/static/js/components/common/EditableSection/index.tsx
For our desired interaction, we only need to call `preventDefault` when the rendering edit button (`readOnly=false`), and not when rendering the edit link (`readOnly=true`). 
N/A
N/A
=> fix: Update EditableSection interaction

amundsen_application/static/js/components/Footer/index.spec.tsx, amundsen_application/static/js/components/Footer/index.tsx, amundsen_application/static/js/ducks/lastIndexed/api/v0.ts, amundsen_application/static/js/ducks/lastIndexed/reducer.ts, amundsen_application/static/js/ducks/lastIndexed/sagas.ts, amundsen_application/static/js/ducks/lastIndexed/tests/index.spec.ts, amundsen_application/static/js/ducks/lastIndexed/types.ts, amundsen_application/static/js/ducks/rootReducer.ts, amundsen_application/static/js/ducks/rootSaga.ts, amundsen_application/static/js/ducks/tableMetadata/api/v0.ts, amundsen_application/static/js/ducks/tableMetadata/reducer.ts, amundsen_application/static/js/ducks/tableMetadata/sagas.ts, amundsen_application/static/js/ducks/tableMetadata/tests/index.spec.ts, amundsen_application/static/js/ducks/tableMetadata/types.ts, amundsen_application/static/js/fixtures/globalState.ts
Currently single reducer is handling states related to tableMetadata and lastIndexed values. To optimize, we decoupled tableMetadata and lastIndexed values and created different reducer to handle lastIndexed state.
Added unit tests
NA
=> fix: Create separate reducer for last indexed value

amundsen_application/api/announcements/v0.py, amundsen_application/static/css/_layouts.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/HomePage/index.tsx, amundsen_application/static/js/components/common/Announcements/AnnouncementsList/index.spec.tsx, amundsen_application/static/js/components/common/Announcements/AnnouncementsList/index.tsx, amundsen_application/static/js/components/common/Announcements/AnnouncementsList/styles.scss, amundsen_application/static/js/components/common/Announcements/index.tsx, amundsen_application/static/js/components/common/Card/index.spec.tsx, amundsen_application/static/js/components/common/Card/index.tsx, amundsen_application/static/js/components/common/Card/styles.scss
Adds the announcements block into the homepage
Wires the cards to the announcements list
Updates maximum container to match designs
Updated tests
=> feat: Wiring announcements block on Homepage

amundsen_application/static/tsconfig.eslint.json
Can't find anywhere this is referenced, in package.json we specify:
```
"parser": "@typescript-eslint/parser",
"parserOptions": {
"project": "tsconfig.json",
"sourceType": "module"
},
```
so i'm pretty sure this is defunct. Tests will tell :) 
=> build: remove defunct eslint tsconfig file

amundsen_application/static/js/components/TableDetail/ResourceReportsDropdown/index.tsx, amundsen_application/static/js/components/TableDetail/constants.ts, amundsen_application/static/js/components/TableDetail/index.tsx
Fixes error on table
Cleans unused text
=> fix: Fixes error on TableDetail on Dev

.github/workflows/pull_request.yml, amundsen_application/static/.betterer.results, amundsen_application/static/.betterer.ts, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/common/Flag/index.spec.tsx, amundsen_application/static/js/components/common/Flag/index.tsx, amundsen_application/static/js/ducks/search/utils.ts, amundsen_application/static/js/fixtures/globalState.ts, amundsen_application/static/package-lock.json, amundsen_application/static/package.json, docs/developer_guide.md
Adds Betterer for checking regressions on our null checks on TypeScript
Plugs it on the workflow
=> build: Adding betterer to workflow

amundsen_application/static/.betterer.results, amundsen_application/static/css/_layouts.scss, amundsen_application/static/css/_typography-default.scss, amundsen_application/static/js/components/AnnouncementPage/index.tsx, amundsen_application/static/js/components/AnnouncementPage/styles.scss, amundsen_application/static/js/components/DashboardPage/index.tsx, amundsen_application/static/js/components/DashboardPage/styles.scss, amundsen_application/static/js/components/ProfilePage/index.tsx, amundsen_application/static/js/components/ProfilePage/styles.scss, amundsen_application/static/js/components/TableDetail/index.tsx, amundsen_application/static/js/components/TableDetail/styles.scss, amundsen_application/static/js/components/common/Announcements/AnnouncementsList/styles.scss, amundsen_application/static/js/components/common/Card/styles.scss, amundsen_application/static/js/components/common/ResourceStatusMarker/styles.scss, amundsen_application/static/js/components/common/SearchBar/index.spec.tsx, amundsen_application/static/js/components/common/SearchBar/index.tsx, amundsen_application/static/js/components/common/SearchBar/styles.scss, amundsen_application/static/js/stories/typography.story.tsx, amundsen_application/static/package-lock.json, docs/developer_guide.md
Refactors away the .h1, .h2 and .h3 text classes
Adds documentation about text and heading styling
Ran tests
Updated some
Added small docs
=> chore: Refactors away the .h1, .h2 and .h3 text classes

amundsen_application/static/.betterer.results, amundsen_application/static/css/_popovers.scss, amundsen_application/static/js/components/TableDetail/ColumnList/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/parser.spec.ts, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/parser.ts, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/styles.scss, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx, amundsen_application/static/js/components/TableDetail/index.tsx
Signed-off-by: Tamika Tannis <ttannis@lyft.com>
This PR:
1. Passes `database` property from `TableDetail` through the column list component to `ColumnType`.
2. Creates `parser.ts` which owns the logic for parsing complex column types for supported databases. It creates an object of the `NestedType` interface.
3. Adds logic to `ColumnType` to render the information in `NestedType`. 
Added some tests for `parser.ts`.
TODO on feature branch before merge:
1. Tests for `parseNestedTypeHelper` after collecting use cases.
2. Still need tests for `ColumnType` interactions
N/A for this feature …
=> feat: Parse column types

amundsen_application/static/js/components/common/Announcements/AnnouncementsList/index.spec.tsx, amundsen_application/static/js/components/common/Announcements/AnnouncementsList/index.tsx
Fixes issue where announcements on homepage show up starting with the latest one
Added a regression test
=> fix: Fixes ordering issue on announcements on homepage

amundsen_application/static/.betterer.results, amundsen_application/static/js/components/common/Alert/AlertIcon.tsx, amundsen_application/static/js/components/common/Alert/alert.story.tsx, amundsen_application/static/js/components/common/Alert/index.spec.tsx, amundsen_application/static/js/components/common/Alert/index.tsx, amundsen_application/static/js/components/common/Alert/styles.scss, amundsen_application/static/js/components/common/SVGIcons/AlertIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/index.tsx, amundsen_application/static/js/components/common/SVGIcons/svgIcons.story.tsx, amundsen_application/static/js/components/common/StorySection/index.tsx
Adds the alerts component
Includes tests and a SVG icon for the alert
Added Storybook story for the component
=> feat: Alerts component

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/index.spec.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/index.tsx, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/parser.spec.ts, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/parser.ts, amundsen_application/static/js/components/TableDetail/ColumnListItem/ColumnType/styles.scss, amundsen_application/static/js/components/TableDetail/SourceLink/index.spec.tsx
This PR completes our code complete criteria for the targeted feature branch.
1. Updates `parser.ts` logic to cover an edge case in Presto types. (Commented as `Case 3.1` in code, case  is included in unit tests)
2. Updates styles based on design QA
3. Support for logging click interaction on the column type button.
1.  Adds improved test coverage for `parser.ts`, using similarly complicated structures found in production.
2. Adds improves test coverage for `ColummnType`
N/A for this feature.
- All the public python functions and the classes in the PR …
=> test: Improves unit tests for ColumnType + QA fixes

amundsen_application/static/js/components/common/Card/styles.scss, amundsen_application/static/js/components/common/ShimmeringResourceLoader/styles.scss, amundsen_application/static/js/components/common/ShimmeringTagListLoader/styles.scss, amundsen_application/static/js/pages/DashboardPage/QueryListItem/styles.scss, amundsen_application/static/js/pages/TableDetailPage/TableIssues/styles.scss, amundsen_application/static/webpack.prod.ts
Using randomized widths negates the effects of css content hashing, as the built content will be different each time due to the random widths. This PR removes those usages, and for now I have just chosen `75%` for widths that need a percentage, and splitting the different between the old max width and min width for others.
N/A but confirmed the build returns the same `contenthash` each time. 
N/A
=> fix: Remove randomized css widths

amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/constants.ts, amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/index.tsx, amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/styles.scss, amundsen_application/static/js/pages/SearchPage/index.tsx
Created a header component for search results.
N/A
=> feat: add search header

amundsen_application/static/.betterer.results, amundsen_application/static/js/components/common/Table/index.spec.tsx, amundsen_application/static/js/components/common/Table/index.tsx, amundsen_application/static/js/components/common/Table/styles.scss, amundsen_application/static/js/components/common/Table/table.story.tsx, amundsen_application/static/js/components/common/Table/testDataBuilder.tsx
Allows users of table to wrap cell values into other components
Added tests
Added storybook
=> feat: Adds ability to use custom component on table

amundsen_application/static/.betterer.results, amundsen_application/static/js/components/common/Alert/index.tsx, amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/styles.scss, amundsen_application/static/js/components/common/SVGIcons/AlertIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/DownIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/UpIcon.tsx, amundsen_application/static/js/components/common/SVGIcons/index.tsx, amundsen_application/static/js/components/common/SVGIcons/svgIcons.story.tsx, amundsen_application/static/js/components/common/SVGIcons/types.ts, amundsen_application/static/js/components/common/Table/index.spec.tsx, amundsen_application/static/js/components/common/Table/index.tsx, amundsen_application/static/js/components/common/Table/styles.scss, amundsen_application/static/js/components/common/Table/table.story.tsx, amundsen_application/static/js/components/common/Table/testDataBuilder.tsx
Adds expandable rows
Adds fixed width
Splits stories in three sections
Lots of them
=> feat: Adds expandable feature to table

docs/configuration.md
fix: the wrong link to documentation files
=> docs: Commanding: Update configuration.md

amundsen_application/static/css/_layouts.scss, amundsen_application/static/css/_variables-default.scss, amundsen_application/static/js/components/ColumnList/styles.scss, amundsen_application/static/js/components/common/Table/index.spec.tsx, amundsen_application/static/js/components/common/Table/index.tsx, amundsen_application/static/js/components/common/Table/styles.scss
Adds padding to table by default based on column alignment
Uses monospace-like font
Tweaks description showing
Updated tests
=> chore: Padding on table and limits on description showing

public.Dockerfile, setup.py
Bumping flaskoidc to version 0.1.0 will allow users to set the redirect url with an environment variable.
Thus, when merged the following two issues can be closed. https://github.com/amundsen-io/amundsenfrontendlibrary/pull/674 and https://github.com/amundsen-io/amundsen/issues/594
After merge I will update Amundsen main repo and I guess we can get to https://github.com/amundsen-io/amundsen/pull/354 too with a few updates to the helm charts reflecting the capabilities of flask v0.1.0.
=> chore: Bumped flaskoidc dependency

requirements.txt
CI marshmallow incompatible version conflicts.
=> fix: relaxed marshmallow requirement to see if conflicts arise

amundsen_application/static/.betterer.results, amundsen_application/static/js/components/ColumnList/index.spec.tsx, amundsen_application/static/js/components/ColumnList/index.tsx, amundsen_application/static/js/components/ColumnList/styles.scss, amundsen_application/static/js/components/ColumnList/testDataBuilder.ts, amundsen_application/static/js/components/common/Table/index.tsx, amundsen_application/static/js/config/config-default.ts, amundsen_application/static/js/config/config-types.ts, amundsen_application/static/js/config/config-utils.ts, amundsen_application/static/js/config/index.spec.ts, amundsen_application/static/js/fixtures/metadata/table.ts, amundsen_application/static/js/interfaces/Resources.ts, amundsen_application/static/js/interfaces/TableMetadata.ts, amundsen_application/static/js/pages/TableDetailPage/ListSortingDropdown/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/ListSortingDropdown/index.tsx, amundsen_application/static/js/pages/TableDetailPage/ListSortingDropdown/styles.scss, amundsen_application/static/js/pages/TableDetailPage/TableDashboardResourceList/index.tsx, amundsen_application/static/js/pages/TableDetailPage/constants.ts, amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/index.tsx, amundsen_application/static/js/pages/TableDetailPage/styles.scss
Adds ability to sort the table columns on the Table detail page
Added tests
=> feat: Adds sortable table detail page

amundsen_application/static/.betterer.results, amundsen_application/static/.storybook/manager.ts, amundsen_application/static/js/components/ColumnList/index.tsx, amundsen_application/static/js/components/common/Table/index.spec.tsx, amundsen_application/static/js/components/common/Table/index.tsx, amundsen_application/static/js/components/common/Table/table.story.tsx, amundsen_application/static/js/components/common/Table/testDataBuilder.tsx
Trying to type the table entry properly, relating the data with the columns
=> chore: Testing types for table input

docs/react_naming_conventions.md
Adds a naming convention for component names and prop names
It is documentation only
=> docs: Adds React components naming conventions

amundsen_application/config.py, amundsen_application/models/data_issue.py, amundsen_application/proxy/issue_tracker_clients/asana_client.py, amundsen_application/proxy/issue_tracker_clients/jira_client.py, requirements.txt, tests/unit/api/issue/test_issue.py, tests/unit/issue_tracker_clients/test_asana_client.py, tests/unit/issue_tracker_clients/test_jira_client.py, tests/unit/models/test_data_issue.py
This adds an AsanaClient alongside the existing JIRA client.
Additionally, I've refactored the JIRA priority map to be a Python Enum that includes both the JIRA priority and severity and has helper methods for creating a priority object based on those values.
I've added one basic test.
I'll happily add documentation if folks are happy with the current state of this PR.
=> feat: Add support for tracking Data Issues via Asana

amundsen_application/static/js/components/ColumnList/ColumnStats/index.spec.tsx, amundsen_application/static/js/components/ColumnList/ColumnStats/index.tsx, amundsen_application/static/js/components/ColumnList/ColumnStats/testDataBuilder.ts, amundsen_application/static/js/utils/index.spec.ts, amundsen_application/static/js/utils/numberUtils.ts
Changed logic so non numerical stats values will not be converted to int.
https://github.com/amundsen-io/amundsen/issues/778
test cases where stats values are dates.
N/A
=> fix: accept non int stats values

amundsen_application/static/.betterer.results, amundsen_application/static/js/components/common/EditableText/index.spec.tsx, amundsen_application/static/js/components/common/EditableText/index.tsx, amundsen_application/static/js/components/common/OwnerEditor/index.tsx, amundsen_application/static/js/interfaces/Dashboard.ts, amundsen_application/static/js/pages/DashboardPage/index.spec.tsx, amundsen_application/static/js/pages/DashboardPage/index.tsx, amundsen_application/static/js/utils/dateUtils.ts, amundsen_application/static/package-lock.json, amundsen_application/static/package.json
Updates ReactMarkdown
Updates TypeScript
Updates moment-timezone
Cleans up some ESLint and TypeScript issues
Updated tests
=> chore: Updating frontend dependencies

tests/unit/api/mail/test_v0.py, tests/unit/api/metadata/test_v0.py, tests/unit/log/test_action_log.py
Signed-off-by: Wonyeong Choi <ciwnyg0815@gmail.com>
- Since the `assertEquals` function has been deprecated, replaced it with the `assertEqual` function for all test files.
- Since the `assertDictContainsSubset` function has been deprecated, replaced it with `assertEqual` and `dict`function.
Passed all existing unit tests
pytest doc about deprecated function
- https://docs.python.org/3.3/library/unittest.html#deprecated-aliases
- https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertDictContainsSubset
=> chore: Change deprecated pytest function

amundsen_application/api/utils/request_utils.py, amundsen_application/config.py
Provide Env Vars to configure a client cert for mTLS.
A client certificate can be specified to present with requests to
metadata and search services for mTLS. The configuration is given
as a pair of paths to the PEM encoded cert and key files. This is
described in more detail in the requests documentation:
https://requests.readthedocs.io/en/master/user/advanced/#client-side-certificates
This assumes that the frontend should present the same client
cert to both the search and metadata services, which is consistent
with the idea that a client cert should uniquely identify the
service that is presenting it.
If the environment variables are not set, then the clients are
created as normal without any expectation of mTLS.
This addresses https://github.com/amundsen-io/amundsen/issues/754
I did …
=> feat: Expose config for mTLS certificates.

amundsen_application/static/js/pages/TableDetailPage/TableHeaderBullets/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/TableHeaderBullets/index.tsx, amundsen_application/static/js/pages/TableDetailPage/index.spec.tsx, amundsen_application/static/js/pages/TableDetailPage/index.tsx
On the table_detail page let's make the 'schema' in the top bar clickable. This should navigate the user to a search page with the schema filter pre-filled with the current schema value. Similarly the 'database' label just below it should also be clickable to do the same with the 'database' value pre-filled. 
Add tests for new links
N/A
=> feat: Make 'schema' and 'database' clickable to initiate a search

amundsen_application/static/js/components/common/BadgeList/index.tsx
Fixed indexing issue that happened with multiple badges in badge list which caused mismatch in badge names and search keyword.
N/A
N/A
=> fix: table with multiple badges not triggering the correct search

requirements.txt
Bumped responses back to version that does not pin urllib3 since it was causing conflict with other dependencies using newer versions of urllib3.
https://github.com/getsentry/responses/blob/30a7fa73e050b72432492e955faead2d37302fb6/CHANGES#L27
N/A
N/A
=> fix: (until they update urllib3) rolling back to v 0.10.15 of responses

amundsen_application/static/.storybook/webpack.config.js, amundsen_application/static/package-lock.json, amundsen_application/static/package.json, amundsen_application/static/webpack.common.ts, amundsen_application/static/webpack.dev.ts, amundsen_application/static/webpack.prod.ts
Followed https://stackoverflow.com/questions/41359504/webpack-bundle-js-uncaught-referenceerror-process-is-not-defined/64553486#64553486 to fix `react_devtools_backend.js:2430 ReferenceError: process is not defined`.
N/A
N/A
=> fix: fixed webpack 5 issue

amundsen_application/api/__init__.py
Issues like https://github.com/amundsen-io/amundsen/issues/822 seem like something is going very wrong with the install, but very commonly it's just a step was missing. In that case, print a human-readable more-helpful error line.
We don't have jinja2 in our requirements -- it's from Flask, but that seems stable enough to be safe
n/a
n/a
=> chore: print human-readable error if index.html isn't found

amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/constants.ts, amundsen_application/static/js/components/common/ResourceList/ResourceListHeader/index.tsx, amundsen_application/static/js/pages/SearchPage/index.tsx
When searching, `ResourceListItem` uses per-resource content classes to sub in the content columns. Thus the header columns need to vary based on the content as well.
Solve that by having the parent of `ResourceListHeader` pass in the types of the current content, and have `ResourceListHeader` swap out labels based on `ResourceType`
It's a bit smelly to me to have a fan-out based on `ResourceType` here. Perhaps ideally `Resource` would have a `columnLabel` method, and `DashboardResource` would override that to show the correct label (same for other subclasses of `Resources`). however AFAICT `DashboardResource` is just an interface, not an object, so I don't know that that's possible. Definitely looking for a better way to do this, this certainly works and isn't horrific, but it is a bit …
=> fix: in search results, change header based on content

amundsen_application/static/.betterer.results, amundsen_application/static/js/pages/DashboardPage/index.tsx
For mode dashboard, we have last run state, for other dashboard type, we don’t have. So in https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/pages/DashboardPage/index.tsx#L323, it will become none. then once it enters https://github.com/amundsen-io/amundsenfrontendlibrary/blob/f5149bcbfbc90013ef169095ed1148d3dc96e016/amundsen_application/static/js/components/common/ResourceStatusMarker/index.tsx#L44 , it throws exception and fails the whole page.
Make last run state optional which fixed the issue. …
=> fix: make last run state in dashboard page optional

amundsen_application/api/mail/v0.py, amundsen_application/api/utils/notification_utils.py, tests/unit/api/mail/test_v0.py, tests/unit/utils/test_notification_utils.py
Allows custom mail clients to work even if the underlying system doesn't return 200 OK. for example sendgrid returns 202 ACCEPTED.
Modified test_send_notification_success to include sub tests for httpSTATUS.OK and .ACCEPTED. 
None
=> fix: notification_utils.send_notification accept all 2xx status codes

.github/CODEOWNERS
I mostly want to approve dependabot PRs right right now.
I'll start reviewing other code as well but would like a second set of 👀 before I start merging alone
=> chore: add dorian to codeowners

requirements.txt, setup.py
pyarrow depenency failed because of a ModuleNotFoundError: No module named 'Cython'. Added it as an extra requirement on setup.py
N/A
N/A
=> fix: pyarrow dependency breaking

amundsen_application/api/metadata/v0.py, amundsen_application/api/utils/request_utils.py, tests/unit/api/metadata/test_v0.py
Signed-off-by: tianru zhou <tianru.zhou@databricks.com>
After add / delete tags for tables in UI, update corresponding tags info in elasticsearch synchronously.
Related SearchService PR: https://github.com/amundsen-io/amundsensearchlibrary/pull/172
- pass all unit tests locally
- manual end-to-end test
=> fix: index tag info into elasticsearch immediately after ui change

.github/workflows/monthly_release.yml, setup.py
=> fix: made change to preserve format of changelog

.github/workflows/monthly_release.yml, .github/workflows/publish_release.yml, setup.py
Added CHANGELOG.md file to persist the changes from the new release, as well as preventing a new release from happening if the setup.py file is changed without a version bump. Release publishing should be triggered when both setup.py and CHANGELOG.md have been changed.
CHANGELOG.md should be overwritten every time and only contain the changes in the newest release.
=> fix: add changelog file

amundsen_application/static/js/ducks/tableMetadata/index.spec.ts, amundsen_application/static/js/interfaces/TableMetadata.ts, amundsen_application/static/js/pages/TableDetailPage/DataPreviewButton/index.tsx
Adds the table cluster to the preview query params, so it can be used when making a preview client. 
useful e.g. for Bigquery tables, where the Google Cloud Project id(The cluster) is needed to query a table for preview data. 
Unsure where to add tests for this. :) Also not sure the change warrants a test. 
=> fix: Add cluster to preview data query 

amundsen_application/static/css/_layouts.scss
Closes https://github.com/amundsen-io/amundsen/issues/912
cc @Golodhros
=> fix: make table details not overlap on safari

.gitignore, amundsen_application/api/preview/v0.py, amundsen_application/api/utils/metadata_utils.py, amundsen_application/base/base_announcement_client.py, amundsen_application/base/base_bigquery_preview_client.py, amundsen_application/base/base_superset_preview_client.py, amundsen_application/base/examples/example_dremio_preview_client.py, amundsen_application/models/announcements.py, amundsen_application/models/preview_data.py, amundsen_application/models/user.py, requirements.txt, setup.py, tests/unit/base/test_announcement_client.py, tests/unit/base/test_superset_preview_client.py, tests/unit/models/test_user.py
This rolls frontend onto marshmallow 3. After this, only gremlin is left to upgrade.
Disclaimer: Marshmallow3 is more strict than its predecessor (e.g. by default does not accept unknown keys) and unless we override that globally - which I do not recommend - there may be API differences that go uncaught in testing. Unlike metadata/search, frontend makes more use of marshmallow so there is more potential for problems. 
Have started up frontend and clicked around to confirm no obvious problems. 
- All the public python functions and the classes in the PR …
=> chore: upgrade to marshmallow 3

amundsen_application/__init__.py, amundsen_application/wsgi.py
In `wsgi.py`, we do:
```
application = create_app(
config_module_class=os.getenv('FRONTEND_SVC_CONFIG_MODULE_CLASS') or 'amundsen_application.config.LocalConfig')
```
So this check of env vars inside `create_app` was duplicated. This is problematic if you use a custom `create_app` invocation, and then accidentally have a `FRONTEND_SVC_CONFIG_MODULE_CLASS` env var present. It might be reasonable to have `create_app` use the env var iff `config_module_class` isn't set (i'm happy to change PR to do that), which I think is more in line with expectations of default vars.
Ran frontend with custom `FRONTEND_SVC_CONFIG_MODULE_CLASS` set, it's picked up.
(ty for @madison-ookla for noticing this irregularity)
=> bug: remove duplicated env var fetch

.github/workflows/pull_request.yml, amundsen_application/__init__.py, amundsen_application/base/base_mail_client.py, amundsen_application/tests/test_utils.py, requirements.txt, tests/unit/api/announcements/test_v0.py, tests/unit/api/issue/test_issue.py, tests/unit/api/mail/test_v0.py, tests/unit/api/metadata/test_v0.py, tests/unit/api/preview/test_v0.py, tests/unit/base/test_issue_tracker_client.py, tests/unit/base/test_preview_client.py, tests/unit/utils/test_metadata_utils.py, tests/unit/utils/test_notification_utils.py, tests/unit/utils/test_response_utils.py, tests/unit/utils/test_search_utils.py
Signed-off-by: Grant Seward <grant@stemma.ai>
This PR addresses issue: https://github.com/amundsen-io/amundsen/issues/974
This PR updates the version of `mypy` in order to make `amundsenfrontend` compatible with Python3.8. The prior version of `mypy` had a bug that prevented it from being installed in Python3.8 but this bug was resolved in 2019. The version was bumped to the newest mypy version (.812), simply because the other Amundsen services were not already aligned on a specific version but I can see that it would also make sense to match the metadata service version (.782). I'll look for feedback here.
There are no material impacts to the code as part of this PR and the majority of the changes are to add explicit typing to several tests. However, the newer version of `mypy` requires …
=> fix: Upgrade mypy version to build with Python3.8

amundsen_application/static/js/pages/TableDetailPage/index.tsx
This PR addresses issue: https://github.com/amundsen-io/amundsen/issues/997
Previously watermarks were only shown for tables that are not views. This removes the validation in the front-end. 
If showing watermarks for views is _absolutely_ required, or if there needs to be more complex logic handling when to show this, the logic can be to move this validation into the metadata service in the future to only return results for eligible tables.
No tests added / updated
N/A
- All the public python functions and the classes in the PR contain docstrings that …
=> fix: Display watermarks for all tables when available
